### ISSUE TITLE
Brightness value does not follow entities brightness scale

### ISSUE THREAD

**Issue by danobot** [thomasloven/lovelace-slider-entity-row#10]
The brightness value is always 100.

```
      - id: 45d05c803c0c4915ab68505568fb7633  # Automatically created id
        type: entities
        entities:
          - id: 4082c0a0cfdc4b5fbe11fa765f688e7f  # Automatically created id
            type: custom:slider-entity-row
            entity: light.tv_led
            show_value: true
```

**Entity**
```
light:
- platform: mqtt
  name: TV Led
  state_topic: "stat/son_tv_led/RESULT"
  command_topic: "cmnd/son_tv_led/POWER"
  state_value_template: "{{ value_json.POWER }}"
  brightness_state_topic: "cmnd/son_tv_led/Dimmer"
  brightness_command_topic: "cmnd/son_tv_led/Dimmer"
  brightness_value_template: "{{ value_json.Dimmer }}"
  brightness: true
  brightness_scale: 100 # max brightness value
  rgb: false
  optimistic: false
```

|Entity | State | Attributes|
-- | -- | --
| light.tv_led | on | brightness: 205 friendly_name: TV Led supported_features: 1 |

I think theres a defect because the slider assumes the brightness scale is 0-255.
If I change the entity state manually in developer tools, I can see the slider udpate correctly in the UI when the entity's brightness is adjusted on a scale of 0-255.

Not sure how to work around this, can the slider query the entities `brightness_scale` value? and use that instead of `255`?
