### ISSUE TITLE
Slider not displayed for entities with nordic characters in friendly name

### ISSUE THREAD

**Issue by BigFam194** [thomasloven/lovelace-slider-entity-row#102]
My Home Assistant version: 0.107.7

My lovelace configuration method (GUI or yaml): GUI
integration installed with HACS

What I am doing:
Adding a simply enitity card. All entities display the slider as expected but the fönster soffan enitity shows as a normal enitity with no slider

entities:
  - entity: light.vardagsrummet_soffan_taklampa
    name: soffan taklampa
    toggle: false
    type: 'custom:slider-entity-row'
  - entity: light.vardagsrummet_matbordet_taklampa
    name: matbordet taklampa
    type: 'custom:slider-entity-row'
  - entity: light.vardagsrummet_bokhylla
    name: bokhylla
    type: 'custom:slider-entity-row'
  - entity: light.vardagsrummet_fonster_soffan
    name: fönster soffan
  - entity: light.vardagsrummet_tv_bordslampa
    name: TV bordslampa
    type: 'custom:slider-entity-row'

What I expected to happen:
I expected all light entities to have sliders.

What happened instead:
All light entities except one with nordic characters in the fiendly name are displayed with sliders as expected but the one which doesn's display like a normal entitiy

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

entities:
  - entity: light.vardagsrummet_soffan_taklampa
    name: soffan taklampa
    toggle: false
    type: 'custom:slider-entity-row'
  - entity: light.vardagsrummet_matbordet_taklampa
    name: matbordet taklampa
    type: 'custom:slider-entity-row'
  - entity: light.vardagsrummet_bokhylla
    name: bokhylla
    type: 'custom:slider-entity-row'
  - entity: light.vardagsrummet_fonster_soffan
    name: fönster soffan
  - entity: light.vardagsrummet_tv_bordslampa
    name: TV bordslampa
    type: 'custom:slider-entity-row'
  - entity: sensor.lumi_lumi_weather_fdf44902_temperature
    name: multisensor - temp
  - entity: sensor.lumi_lumi_weather_fdf44902_humidity
    name: multisensor - luftfuktighet
  - entity: sensor.lumi_lumi_weather_fdf44902_pressure
    name: multisensor - lufttryck
  - entity: vacuum.vardagsrummet_roborock
title: 'Vardagsrummet (''custom:slider-entity-row'')'
type: entities


# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Ta en titt till på vad som skiljer
```yaml
- entity: light.vardagsrummet_fonster_soffan
  name: fönster soffan
```
från t.ex.
```yaml
- entity: light.vardagsrummet_matbordet_taklampa
  name: matbordet taklampa
  type: 'custom:slider-entity-row'
```
