### ISSUE TITLE
Expected a value of type

### ISSUE THREAD

**Issue by kyote73** [thomasloven/lovelace-slider-entity-row#103]
My Home Assistant version: 0.107.5

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Adding a slider with toggle to an entity in a card

What I expected to happen:
No error when editing Entities Card Configuration (Code Editor)

What happened instead:
I receive an error "Expected a value of type `{entity,name,icon} | entity-id` for `entities.0.toggle` but received `true`."

**Minimal** steps to reproduce:
entities:
  - entity: light.master_bedroom_bedroom_light_162
    name: Light
    toggle: true
    type: 'custom:slider-entity-row'

```yaml
# The least ammount of code possible to reproduce my error
entities:
  - entity: light.master_bedroom_bedroom_light_162
    name: Light
    toggle: true
    type: 'custom:slider-entity-row'


# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[ X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X ] Have made sure I am using the latest version of the plugin.

[X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
