### ISSUE TITLE
Slider do not fit screen in android app

### ISSUE THREAD

**Issue by fabsss** [thomasloven/lovelace-slider-entity-row#106]
My Home Assistant version: 0.107.7, Android App v 1.8.0-144, Android 10, Samsung S10e

My lovelace configuration method (GUI or yaml): yaml

What I am doing: Looking at the slider in hass-app on Android

What I expected to happen: Slider fit the screen

What happened instead: values on the right side of slider are truncated

**Minimal** steps to reproduce:

```yaml
entities:
  - entity: light.reading_light
    type: 'custom:slider-entity-row'
    name: Leselampe
    step: 1
  - entity: light.reading_light_room_light
    type: 'custom:slider-entity-row'
    step: 1
    name: Raumlicht
  - entity: light.stehlampe
    type: 'custom:slider-entity-row'
    attribute: color_temp
    name: Farbtemperatur
title: Stehlampe
type: entities

# End of code
```

Error messages from the browser console:
none

Screenshot:
![Screenshot_20200407-152213_Home Assistant](https://user-images.githubusercontent.com/35114731/78674872-8d7ede80-78e4-11ea-83eb-d174abf18e5a.jpg)

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
