### ISSUE TITLE
Brightness goes down but not back up

### ISSUE THREAD

**Issue by OckertM** [thomasloven/lovelace-slider-entity-row#108]
My Home Assistant version: 0.108.2

My lovelace configuration method (GUI or yaml): 
yaml

What I am doing: 
using it with lovelace entities card (standard lovelace brightness slider works on lights)

What I expected to happen:
When I pull the slider down and up the state of the lights should follow

What happened instead:
The brightness follows as I go down, off at far left but as soon as I pull it to any value above far left the lights only go to the last minimal brightness.

**Minimal** steps to reproduce:
Make sure light is on, drag brightness down and release once somewhere midway and somewhere near 10%, pull down to zero and release. pull brightness back up to 50 or 100 to find it not working.

# The least ammount of code possible to reproduce my error
```yaml
      - type: entities
        toggle: false
        show_header_toggle: false
        entities:
          - type: custom:slider-entity-row
            entity: light.gerard_bed_left
            name: Bed
            toggle: true
# End of code
```
tested with explicitly putting `attribute: brightness' in as well with no change

Error messages from the browser console:
from what I can find Browser (ctrl+shift+J) logs, `Autofocus processing was blocked because a document already has a focused element.`. nothing in Developer Tools>Logs, no errors found.

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[ X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[ X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
