### ISSUE TITLE
full_row: true not displaying correctly on mobile

### ISSUE THREAD

**Issue by Stijn-Daniels** [thomasloven/lovelace-slider-entity-row#110]
My Home Assistant version: 0.108.6

My lovelace configuration method (GUI or yaml): yaml

What I am doing: using the custom:slider-entity-row in an entities list with the option full_row: true

What I expected to happen: slider streched over the full screen with to the left of the slider the current state.

What happened instead: 
on my desktop it is displayed correctly. 
on my phone in the official android app the current state is not displayed

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
          entities: 
            - type: custom:slider-entity-row
              entity: climate.verwarming
              full_row: true
          type: entities
# End of code
```

Error messages from the browser console:
none

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
