### ISSUE TITLE
Bug: lovelace-slider-entity-row into a Picture Elements Card

### ISSUE THREAD

**Issue by caiosweet** [thomasloven/lovelace-slider-entity-row#112]
My Home Assistant version: **0.108.6**
My lovelace configuration method **yaml**.
![input_number](https://user-images.githubusercontent.com/24454580/79687403-43342080-8247-11ea-965f-92f22d11be5b.gif)

What I am doing:
Insert lovelace-slider-entity-row into a Picture Elements Card

What I expected to happen:
It worked before the last updates

What happened instead:
It does not work anymore

**Minimal** steps to reproduce:
Insert this card in picture-elements card

```yaml
# The least ammount of code possible to reproduce my error
type: picture-elements
image: "http://placekitten.com/g/492/277"
elements: 
- type: custom:slider-entity-row
entity: input_number.demo
style: {left: 50%, top: 50%}
# End of code
```

Error messages from the browser console:
I don't know, but in the home assistant log I have this
**ResizeObserver loop limit exceeded**

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
