### ISSUE TITLE
Slider do not fit screen on android app or browser 

### ISSUE THREAD

**Issue by sentinel43** [thomasloven/lovelace-slider-entity-row#115]
My Home Assistant version: 0.108.8

My lovelace configuration method (GUI or yaml): GUI

What I am doing:  Slider at the home assistant app on android phone or via chrome browser on android phone.

What I expected to happen: Slider fit the screen

What happened instead:

In version 11, slider was truncated and position numbers were cutted on the edge of the screen
In version 12, slider goes to the end of the right side of the screen, no position numbers at all, probably they are out of the screen

**Minimal** steps to reproduce:

```yaml

cards:
  - entities:
      - entity: cover.shelly_shsw_25_5db747
        step: 5
        type: 'custom:slider-entity-row'
      - entity: cover.shelly_shsw_25_744f01
        step: 5
        type: 'custom:slider-entity-row'
      - entity: cover.shelly_shsw_25_744f0a
        step: 5
        type: 'custom:slider-entity-row'
      - entity: cover.shelly_shsw_25_73c178
        step: 5
        type: 'custom:slider-entity-row'
      - entity: cover.shelly_shsw_25_730879
        step: 5
        type: 'custom:slider-entity-row'
      - entity: cover.shelly_shsw_21_5593ab
        step: 5
        type: 'custom:slider-entity-row'
      - entity: cover.shelly_shsw_21_134990
        step: 5
        type: 'custom:slider-entity-row'
      - entity: cover.shelly_shsw_21_134f70
        step: 5
        type: 'custom:slider-entity-row'
      - entity: cover.shelly_shsw_21_1354dd
        step: 5
        type: 'custom:slider-entity-row'
    type: entities
popup: timeout
title: Rolete dnevni boravak
type: 'custom:love-lock-card'

# End of code
```

Error messages from the browser console: no error message

Slider entity row v11 installed

![image](https://user-images.githubusercontent.com/54589854/80181603-7559cf80-8605-11ea-810d-260f6b20d23e.png)

Slider entity row v12 installed

![image](https://user-images.githubusercontent.com/54589854/80181514-4cd1d580-8605-11ea-9137-5de491db302f.png)

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[ x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[ x] Have made sure I am using the latest version of the plugin.

[x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[ x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
