### ISSUE TITLE
Toggle switches disappear at narrower column widths

### ISSUE THREAD

**Issue by ntompson** [thomasloven/lovelace-slider-entity-row#124]
My Home Assistant version: 0.109.6

My lovelace configuration method (GUI or yaml): yaml

#### What I am doing:
I use `slider-entity-row` to provide brightness control for my light switches. For example:

```yaml
  # Lounge lights
  - title: Lounge
    type: entities      
    entities:
      - entity: light.lounge
        hide_when_off: true
        min: 5
        name: Main lights
        toggle: true
        type: 'custom:slider-entity-row'
```

#### What I expected to happen:
For all column widths, I expect the slider and toggle switch to appear.

#### What happened instead:
For narrower column widths, the toggle switch disappears.

Wider:

<img width="428" alt="Screen Shot 2020-05-17 at 4 57 40 pm" src="https://user-images.githubusercontent.com/32885870/82137921-880ba100-985f-11ea-9f5d-3ba714a01f29.png">

Narrower:

<img width="307" alt="Screen Shot 2020-05-17 at 4 58 08 pm" src="https://user-images.githubusercontent.com/32885870/82137926-978aea00-985f-11ea-8cc3-6be13ed88411.png">

This happens on Chrome and Safari on macOS (all at latest versions).

#### **Minimal** steps to reproduce:

As described above.

#### Error messages from the browser console:

No relevant error messages from console.

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
