### ISSUE TITLE
cover slider doesnt show 'open' 'closed', but percentage

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-slider-entity-row#138]
My Home Assistant version: 0.111.4

My lovelace configuration method (GUI or yaml):
yaml

What I am doing:
```
  - type: entities
    title: Ikea Raamsverduistering
    show_header_toggle: false
    entities:
      - entity: cover.raamverduistering_stookhok
        name: Stookhok
      - type: custom:slider-entity-row
        entity: cover.raamverduistering_stookhok
        hide_state: false
        full_row: true
```

What I expected to happen:

have slider show state  just like the example in the docs:

<img width="429" alt="Schermafbeelding 2020-06-27 om 23 52 36" src="https://user-images.githubusercontent.com/33354141/85932946-8eb31c80-b8d1-11ea-8c7f-fd7985389fc9.png">

What happened instead:

<img width="355" alt="Schermafbeelding 2020-06-27 om 23 54 52" src="https://user-images.githubusercontent.com/33354141/85932952-a1c5ec80-b8d1-11ea-9500-45d995ff6809.png">

and 

<img width="361" alt="Schermafbeelding 2020-06-27 om 23 55 49" src="https://user-images.githubusercontent.com/33354141/85932966-cde16d80-b8d1-11ea-99b6-aff8d87103ce.png">

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error



# End of code
```

Error messages from the browser console:

none specific to the cover, or slider-entity-row
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [ ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [ ] Have made sure I am using the latest version of the plugin.
- [ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
