### ISSUE TITLE
Full_row but with icon

### ISSUE THREAD

**Issue by enryf89** [thomasloven/lovelace-slider-entity-row#139]
Hello everyone,
I'd like to have the possibility to have a full-width slider like when using the `full_row: true` option, but with the possibility to set an icon on the left.

Right now the only alternative I have found is using the options
`full_row: false`
`name: ' '`
but this leaves a gap between the icon and the slider.

thanks guys and keep up the good work.
Enrico

**Comment by KTibow** [comment]
You can try the zero-width joiner: Go to [here](https://emojipedia.org/zero-width-joiner/) and press the copy button.

**Comment by david-kalbermatten** [comment]
## Visual Example
I think that @enryf89 had something similar to this in mind. (Cobbled it together with paint.net :D).
```yaml
type: entities
show_header_toggle: false
entities:
  - type: 'custom:slider-entity-row'
    attribute: brightness
    entity: light.rgbw_bed_light
    toggle: true
  - type: 'custom:slider-entity-row'
    attribute: white_value
    entity: light.rgbw_bed_light
    full_icon: 'mdi:white-balance-sunny' # idea for how to add icon to config
    full_row: true
    hide_state: false
```
>Slider 1 is brightness, Slider 2 is white_value.

![image](https://user-images.githubusercontent.com/45201085/87851537-ee617e00-c8f9-11ea-8199-ec37b5fd491d.png)

**Comment by enryf89** [comment]
Yes, exactly, @david-kalbermatten got it 100% right.

I'd like to have only the icon and the large slider.

thanks

**Comment by enryf89** [comment]
> You can try the zero-width joiner: Go to [here](https://emojipedia.org/zero-width-joiner/) and press the copy button.

Thank you @KTibow for the suggestion, I tried that, but I have the empty space between the icon and the slider like this:

![Screenshot 2020-07-20 at 12 59 38](https://user-images.githubusercontent.com/9007104/87930775-f13ea900-ca88-11ea-8df2-30d1cb51befb.png)


 I'd prefer it like @david-kalbermatten mockup.

**Comment by david-kalbermatten** [comment]
@enryf89 Would you mind sharing the code for the color presets? Looks interesting :D

**Comment by enryf89** [comment]
here it is (only the colored buttons part):

```
entities:
  - colors:
      - color_name: white
        icon_color: 'linear-gradient(15deg,azure,white)'
        transition: 5
      - color_name: tomato
        icon_color: 'linear-gradient(15deg,red,tomato)'
        transition: 5
      - color_name: orange
        icon_color: 'linear-gradient(15deg,coral,orange)'
        transition: 5
      - color_name: gold
        icon_color: 'linear-gradient(15deg,gold,yellow)'
        transition: 5
      - color_name: green
        icon_color: 'linear-gradient(15deg,limegreen,yellowgreen)'
        transition: 5
      - color_name: royalblue
        icon_color: 'linear-gradient(15deg,mediumblue,royalblue)'
        transition: 5
      - color_name: darkmagenta
        icon_color: 'linear-gradient(15deg,darkmagenta,darkorchid)'
        transition: 5
    entity: light.led_salotto
    justify: around
    type: 'custom:rgb-light-card'
```
