### ISSUE TITLE
Problem with volume current value on media player control

### ISSUE THREAD

**Issue by yinonco** [thomasloven/lovelace-slider-entity-row#151]
My Home Assistant version: 0.114.4

My lovelace configuration method (GUI or yaml):
entities:
      - type: custom:slider-entity-row
        entity: media_player.magnifi_max
        name: Volume

What I am doing:
when trying to set the volume to 20 for example the actual volume state is:
volume_level: 0.20000000298023224
(does not matter if I set it thorough the slider or media_player.volume_set service)
and since `lovelace-slider-entity-row/src/media-player-controller.js` line 8 is using `Math.Ceil` and not `Math.Round`
(`Math.ceil(this.stateObj.attributes.volume_level*100.0);`)
the slider shows volume of 21% even though the actual volume is 20

What I expected to happen:
The slider should show a volume of 20% and not 21%

What happened instead:
The slider shows 21%

**Minimal** steps to reproduce:
Try to set the volume for 20% in a google cast device (Polk MagniFi Max and Mini in my case)

```yaml
# The least ammount of code possible to reproduce my error
entities:
      - type: custom:slider-entity-row
        entity: media_player.magnifi_max
        name: Volume
# End of code
```

Error messages from the browser console:
There are no errors since this is a logic problem

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
