### ISSUE TITLE
Entity Card and header toggle issue

### ISSUE THREAD

**Issue by inconsx** [thomasloven/lovelace-slider-entity-row#153]
My Home Assistant version: 0.116.1

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Create Entity Card for a group of lights

What I expected to happen:
Display header toggle for this group of lights to turn on/off all at once

What happened instead:
header toggle is missing as I can remember with HA version 0.116.x

**Minimal** steps to reproduce:
Create Entity Card with attribute 'show_header_toggle: true' doesn't have any affect

```yaml
# The least ammount of code possible to reproduce my error

show_header_toggle: true
entities:
  - entity: light.dimmable_light_3
    name: Michael
    type: 'custom:slider-entity-row'
  - entity: light.dimmable_light_2
    name: Sabine
    type: 'custom:slider-entity-row'
title: Schlafzimmer
type: entities
theme: Google Dark Theme


# End of code
```

Error messages from the browser console:
n/a

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

![image](https://user-images.githubusercontent.com/22166678/95556947-62508580-0a14-11eb-9008-e0538b35b13c.png)
