### ISSUE TITLE
after upgrading to 0.116 - all sliders disappeared

### ISSUE THREAD

**Issue by adizag** [thomasloven/lovelace-slider-entity-row#154]
![Screenshot_20201012-125935](https://user-images.githubusercontent.com/17390016/95733533-f3c92d00-0c8a-11eb-9118-1606940ccf28.png)
My Home Assistant version: 0.116.2

My lovelace configuration method (GUI or yaml): GUI, installed slider-entity-row from HACS

What I am doing:
updated to 0.116, then nothing.
updated to the latest. uninstalled. installed again.

What I expected to happen:
have slider-entity-row entities in front end

What happened instead:
All slider-entity-row elements disappeared.

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

entities:
  - entity: cover.slvn_prgvlh
    type: 'custom:slider-entity-row'
  - entity: cover.slvn_ymyn
    type: 'custom:slider-entity-row'
  - entity: cover.slvn_shml
    type: 'custom:slider-entity-row'
  - entity: cover.slvn_khzyt_qdmyt
    type: 'custom:slider-entity-row'
  - entity: cover.khdr_mshpkhh
    type: 'custom:slider-entity-row'
  - entity: cover.mtbkh_rshy
    type: 'custom:slider-entity-row'
  - entity: cover.mtbkh_ymyn
    type: 'custom:slider-entity-row'
  - entity: cover.mtbkh_shml
    type: 'custom:slider-entity-row'
show_header_toggle: false
title: תריסים - קומה ראשונה
type: entities

# End of code
```

Error messages from the browser console:
None

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

TNX!

**Comment by adizag** [comment]
Hi @thomasloven , you closed it without any comment...
What shall I do?

**Comment by thomasloven** [comment]
Follow the issue template and provide evidence of having followed the debugging steps in the readme file.

**Comment by adizag** [comment]
sorry, the template was not loading in my original issue opening...
Just updated.

TNX!

**Comment by pilot1981** [comment]
I also have sam issue in 0.116.4: there is some bugs?

**Comment by cslux** [comment]
I have this error too, although not every time. 

Logger: frontend.js.latest.202010012
Source: components/system_log/__init__.py:193
First occurred: October 20, 2020, 2:55:30 PM (63 occurrences)
Last logged: 11:01:50 PM

https://... /hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js:1:2690 Uncaught TypeError: Cannot convert undefined or null to object

https://... /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js:1:1666 Uncaught TypeError: Cannot convert undefined or null to object

https://... /hacsfiles/battery-state-card/battery-state-card.js:1:42 Uncaught TypeError: Cannot convert undefined or null to object

https://... /hacsfiles/vacuum-card/vacuum-card.js:522:37155 Uncaught TypeError: Class extends value undefined is not a constructor or null

https://... /hacsfiles/mini-humidifier/mini-humidifier-bundle.js:1:58818 Uncaught TypeError: Class extends value undefined is not a constructor or null

**Comment by cslux** [comment]
Seems to happen on the mobile devices only (Phone/Tablet). Though I think it's more of a hass problem I guess.

**Comment by cslux** [comment]
I have switch to the manual configuration mode of the lovelace dashboards. The custom component configuration has therefore moved from the frontend integration configuration to the lovelace integration configuration. Since than it never happened again. So seems to be indeed some hass/hacs problem.

Thanks for making such a wonderful card!

**Comment by adizag** [comment]
@thomasloven 
Do you need any more information from me in order to solve this?
I'll be glad to assist.

**Comment by adizag** [comment]
The problem was fixed somehow in version 0.117.2

![image](https://user-images.githubusercontent.com/17390016/97978820-cf1e2c00-1dd6-11eb-9adc-dbdd84a035c1.png)

**Comment by adizag** [comment]
And 3 hours later, it's again missing...
HA wasn't restarted, everything was as it was left.

Your assistant will be appreciated.

**Comment by cslux** [comment]
@adizag I'm pretty sure this has nothing to do with this custom module, but rather with HACS/HA. 

When that happened to me I had this configuration in my `config/configuration.yaml` (https://www.home-assistant.io/integrations/frontend/).
``` yaml
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    - /hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js
    - /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    - /hacsfiles/rgb-light-card/card.js
    - /hacsfiles/mini-humidifier/mini-humidifier-bundle.js
```

When I switched to manual lovelace mode that issue never ever appeared again (https://www.home-assistant.io/lovelace/dashboards-and-views/).

lovelace.yaml
``` yaml
mode: yaml
resources:
  - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js
    type: module
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/mini-climate-card/mini-climate-card-bundle.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/mini-humidifier/mini-humidifier-bundle.js
    type: module
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: module
  - url: /hacsfiles/rgb-light-card/card.js
    type: module
  - url: /hacsfiles/vacuum-card/vacuum-card.js
    type: module
  - url: /hacsfiles/battery-state-card/battery-state-card.js
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
dashboards:
 ...
```
configuration.yaml
``` yaml
lovelace: !include lovelace.yaml
```
