### ISSUE TITLE
From version 0.116 header_toggle do not reflects state of ‘custom:slider-entity-row’ and do not control it’s state

### ISSUE THREAD

**Issue by WildRat** [thomasloven/lovelace-slider-entity-row#155]
My Home Assistant version: 0.116.1

My lovelace configuration method (GUI or yaml):
yaml

What I am doing:
Put ‘custom:slider-entity-row’ in entities card

What I expected to happen:
Header_toggle of entities card to reflect state of ‘custom:slider-entity-row’ and to control it’s state

What happened instead:
Header_toggle do not reflects state of ‘custom:slider-entity-row’ and do not control it’s state

**Minimal** steps to reproduce:
[https://community.home-assistant.io/t/0-116-entities-card-row-editor-restore-snapshots-and-performance-metrics/233438/171?u=wildrat](url)

```yaml
# The least ammount of code possible to reproduce my error
entities:
  - entity: light.sonoff_1000dce2cc
    name: Основной свет
  - entity: light.sonoff_1000d0448f
    name: Торшер
    toggle: true
    type: 'custom:slider-entity-row'
title: Освещение в доме
type: entities
# End of code
```

Error messages from the browser console:
SLIDER-ENTITY-ROW 1.0.0 IS INSTALLED 

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
