### ISSUE TITLE
Slider doesn't reflect brightness level

### ISSUE THREAD

**Issue by inconsx** [thomasloven/lovelace-slider-entity-row#160]
My Home Assistant version: 0.116.4

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Managing my hue bulbs. Switch on/off , dimm up and down via hue smart button.
I use as gateway the deconZ conbee usb stick II.

What I expected to happen:
When I dimm my bulps why hue smart button. I expect that the slider reflects the brightness level.

What happened instead:
Every brightness level is shown as 0 when I dimm up and down my bulps

**Minimal** steps to reproduce:
switch on the bulbs via smart button.
Dimm the bulbs by press and hold the button (bulbs dimm up and down)
slider doesn't show any correct percentage but zero.

```yaml
# The least ammount of code possible to reproduce my error

show_header_toggle: true
entities:
  - entity: light.dimmable_light_3
    name: Michael
    type: 'custom:slider-entity-row'
  - entity: light.dimmable_light_2
    name: Sabine
    type: 'custom:slider-entity-row'
title: Schlafzimmer
type: entities
theme: Google Dark Theme

# End of code
```

Error messages from the browser console:
n/a

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
