### ISSUE TITLE
Attribute 'not fixed' to domain

### ISSUE THREAD

**Issue by fbacker** [thomasloven/lovelace-slider-entity-row#161]
Setting the attribute dynamic based on attribute value would allow to use any attribute in the entity.

Example entity ```input_number.playroom_1_adjust``` with attributes

```
initial: null
editable: true
min: 0
max: 100
step: 1
mode: slider
friendly_name: Fotölj 1
range_min: 23 <!-- custom
range_max: 77 <!-- custom
```

Set the value to these custom attributes

```
type: entities
title: Options
entities:
  - type: custom:slider-entity-row
    entity: input_number.playroom_1_adjust
    attribute: range_max
```
