### ISSUE TITLE
Toogle: true not working

### ISSUE THREAD

**Issue by MauricioXavier13** [thomasloven/lovelace-slider-entity-row#174]
My Home Assistant version: 2021.2.3

My lovelace configuration method (GUI or yaml):
Yaml entities card

What I am doing:
Trying to have toogle instead of state. 
Hide when off is working

What I expected to happen:
To show toggle button to control the light

What happened instead:
Not toggle shown. Only state info.

**Minimal** steps to reproduce:

```yaml
# yaml code in entities card

type: entities
  entities:
  - type: 'custom:slider-entity-row' 
    entity: light.bedside_lamp
    hide_when_off: true
    toggle: true

# End of code
```

Already tried with ikea lamps and the scenario is the same. Only showing state and not toggle. 
What can i have impacting this behaviour?

Thanks and congratz for the work!
