### ISSUE TITLE
Hide_when_off not working for Climate entity

### ISSUE THREAD

**Issue by BigManDave** [thomasloven/lovelace-slider-entity-row#176]
My Home Assistant version: core-2021.3.3

My lovelace configuration method (GUI or yaml): yaml

What I am doing: Adding slider for climate entity and enable hide when off

What I expected to happen: The slider to be hidden when the state of the climate entity is off

What happened instead: The slider is not hidden

**Minimal** steps to reproduce:

```yaml

              - entity: climate.living_room
                full_row: true
                hide_when_off: true
                hide_state: false
                min: 18
                max: 25
                type: 'custom:slider-entity-row'

```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
