### ISSUE TITLE
Celsius unit falls under value for climate entities under certain circumstances

### ISSUE THREAD

**Issue by lenwar** [thomasloven/lovelace-slider-entity-row#184]
My Home Assistant version: 2021.3.4

My lovelace configuration method (GUI or yaml):
yaml

What I am doing:
Adding sliders for thermostats (climate entities). I want to use 0.5 (degrees) as a step, but under certain circumstances, the Celsius unit drops to the next line.

What I expected to happen:
The Celsius unit to stay behind the number

What happened instead:
The Celsius unit sometimes falls under the number.
This behaviour happens during editing on my desktop (windows 10 using Edge) and when using the dashboard on my phone (iPhone 11) with the current app (2021.4).
(see screenshots)

It looks okay on my desktop when using the dashboard

**Minimal** steps to reproduce:
Add the 'step' attribute and give it: 0.5 for a climate entity

```yaml
# The least amount of code possible to reproduce my error
type: entities
entities:
  - type: 'custom:slider-entity-row'
    entity: climate.generieke_thermostaat_woonkamer
    step: 0.5
# End of code
```

Error messages from the browser console:
N/A
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

![screenshot_phone](https://user-images.githubusercontent.com/3773186/113707401-24d96600-96e0-11eb-87ed-dea40b10e3f7.jpeg)

![screenshot_bewerken_desktop](https://user-images.githubusercontent.com/3773186/113707926-e4c6b300-96e0-11eb-9409-d98ac4edd391.png)
