### ISSUE TITLE
Show slider based on supported_features, but that's a deprecated feature in HA 

### ISSUE THREAD

**Issue by pascalwinters** [thomasloven/lovelace-slider-entity-row#191]
My Home Assistant version: core-2021.5.1

My lovelace configuration method (GUI or yaml):
```
- entity: light.brynxz_lamp
  secondary_info: brightness
  type: 'custom:slider-entity-row'
  toggle: true
```
What I am doing:
Set light off

What I expected to happen:
Show slider with dimlevel 0

What happened instead:
Slider is hidden

**Minimal** steps to reproduce:

```yaml
State from developer tools:
supported_color_modes:
  - brightness
friendly_name: Brynxz lamp
icon: 'hass:floor-lamp'
supported_features: 0

```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
