### ISSUE TITLE
Sliders not visible since 2021-05 update for light-group entities if the light is off

### ISSUE THREAD

**Issue by DanielWinks** [thomasloven/lovelace-slider-entity-row#194]
My Home Assistant version: 2021.05.x

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Adding light group to UI with slider visible

What I expected to happen: Visible slider

What happened instead: No visible slider until light is turned on

**Minimal** steps to reproduce: Create light group, add light group entity to UI

```yaml
# UI
entity: light.family_room_overhead_light
type: 'custom:slider-entity-row'
toggle: true
name: Family Room
```
```yaml
# Light group (this is 4 identical RGBW bulbs, Inovelli Ilumin specifically)
light:
  - platform: group
    name: Family Room Overhead Light
    entities:
      - light.family_room_overhead_rgbw1
      - light.family_room_overhead_rgbw2
      - light.family_room_overhead_rgbw3
      - light.family_room_overhead_rgbw4
```
Error messages from the browser console:
None
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
