### ISSUE TITLE
Slider missing when light is off

### ISSUE THREAD

**Issue by ZEi20T** [thomasloven/lovelace-slider-entity-row#199]
My Home Assistant version: 2021.6.0

My lovelace configuration method (GUI or yaml): YAML

What I am doing: Use slider when light is off to set to X percentage

What I expected to happen: Drag slider to required location

What happened instead: Slider is missing after todays update to version 17.1

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

  - type: custom:slider-entity-row
    entity: light.light_name
    toggle: true

# End of code
```

Error messages from the browser console:

N/A

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
