### ISSUE TITLE
Seeing lag, only when turning device on.

### ISSUE THREAD

**Issue by flyize** [thomasloven/lovelace-slider-entity-row#202]
My Home Assistant version: 2021.6.6

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Turning on a switch.

What I expected to happen: No lag, switch turns on.

What happened instead: UI shows switch turning back off, then coming back on after about 2-3 seconds. This works without issue with a regular Entities card.

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
type: entities
entities:
  - type: custom:slider-entity-row
    entity: light.kitchen_overhead_lights
    name: Kitchen Overheads
    toggle: true
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
