### ISSUE TITLE
"hidden_when_off" slider disappears despite the entity not being off

### ISSUE THREAD

**Issue by iD4NG3R** [thomasloven/lovelace-slider-entity-row#210]
My Home Assistant version: 2021.8.4

My lovelace configuration method (GUI or yaml):
GUI, although most objects are then configured using yaml

What I am doing:
Showing the brightness slider of a light only when said light is on.

What I expected to happen:
The slider showing when the brightness is between 1 and 255 (inclusive) and the device is on.

What happened instead:
The slider disappears when the value is set to 1 using said slider.
The slider shows the value being 5 when setting the brightness of the entity to 1 through the entity itself.

![](https://i.imgur.com/22UeMeG.gif)

**Minimal** steps to reproduce:
Add a slider that is hidden_when_off
Use the slider to set the value of a light to 1
Watch the slider disappear

```yaml
# The least ammount of code possible to reproduce my error
type: entities
entities:
  - entity: light.name
    name: Some cool name
  - type: custom:slider-entity-row
    entity: light.name
    hide_when_off: true
    full_row: true
    min: 1   # not setting a min or max, or changing min to 0 does not affect the behaviour, 
    max: 255 # it will disappear regardless of the value
    attribute: brightness
# End of code
```

Error messages from the browser console:
none.
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
