### ISSUE TITLE
Slider doesnt scale with CSS zoom.

### ISSUE THREAD

**Issue by cbishop76** [thomasloven/lovelace-slider-entity-row#214]
My Home Assistant version: core-2021.9.7

My lovelace configuration method (GUI or yaml): yaml

What I am doing: Using css zoom: 0.5 (to counteract a device that forces 200% zoom in the browser)

What I expected to happen: The distance the user slides will match the visual length of the slider

What happened instead: The distance the user slides matches the "unzoomed" length of the slider

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
- type: entities
  title: Outside
  card_mod:
	style: |
	  ha-card {
		zoom: 0.5;
	  }
  entities:
	- entity: light.exterior_porch_lights
	  name: Porch
	  toggle: true
	  type: 'custom:slider-entity-row'
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
