### ISSUE TITLE
Light group of 1 not showing correctly

### ISSUE THREAD

**Issue by SeLLeRoNe** [thomasloven/lovelace-slider-entity-row#219]
My Home Assistant version: core-2021.10.6

My lovelace configuration method (GUI or yaml): YAML

What I am doing: Using slider-entity-row with light group which contains only 1 light

What I expected to happen: For the slider to work as normal

What happened instead: The slider doesn't appear

**Minimal** steps to reproduce:

Card:
```yaml
# The least ammount of code possible to reproduce my error
  - type: custom:slider-entity-row
    entity: light.patio_lights
    name: Patio
    toggle: true
    hide_state: true
    hide_when_off: false
    full_row: false
    min: 0
    max: 100
    step: 1

# End of code
```
Light group:
```yaml
# The least ammount of code possible to reproduce my error

---
platform: group
name: Patio Lights
entities:
  - light.patio_led1624g9_wall

# End of code
```

Error messages from the browser console:
None
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
