### ISSUE TITLE
Fan Icon doesn't update and Fan toggle requires 2 activations to turn off

### ISSUE THREAD

**Issue by TiddlyWiddly** [thomasloven/lovelace-slider-entity-row#226]
My Home Assistant version: 2021.11.1

My lovelace configuration method (GUI or yaml): yaml

What I am doing: Turning on the fan and turning off the fan

What I expected to happen: I expected that the toggle would turn off the fan. I expected that the icon would update with status change when turned on.

What happened instead: I have to activate the toggle twice to turn off the fan. The status is not reflected in the icon when the toggle is turned on.

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
type: entities
entities:
  - type: custom:slider-entity-row
    entity: fan.office_fan
    toggle: true
title: Switches
state_color: true

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
