### ISSUE TITLE
Climate entity attribute

### ISSUE THREAD

**Issue by MightyBoo** [thomasloven/lovelace-slider-entity-row#227]
Hi Thomas,

Using `attribute: fan_modes` does not work. Is there any way, for the slider to represent `fan_modes` instead of the default `temperature`?

Thank you! 😊😊

This is the Lovelace  card code:

```
type: entities
entities:
  - entity: climate.air_con
    name: Air Con
    type: custom:slider-entity-row
    toggle: true
    hide_when_off: true
    min: 18
    max: 26
```

This is the Daikin Air Conditioner default integration entity `climate.air_con` :

```
hvac_modes:
  - fan_only
  - dry
  - cool
  - heat
  - heat_cool
  - 'off'
min_temp: 7
max_temp: 35
target_temp_step: 1
fan_modes:
  - Auto
  - Silence
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
preset_modes:
  - none
  - away
  - eco
  - boost
swing_modes:
  - 'Off'
  - Vertical
  - Horizontal
  - 3D
current_temperature: 28
temperature: 18
fan_mode: '5'
hvac_action: 'off'
preset_mode: none
swing_mode: 3D
friendly_name: Air Con
icon: mdi:air-conditioner
supported_features: 57
```
