### ISSUE TITLE
Slider does not work with HA 2022.3.3?

### ISSUE THREAD

**Issue by andrewbpowers** [thomasloven/lovelace-slider-entity-row#241]
Hello!

I use HA 2022.3.3 and try to install the slider.

First i opened this file (https://github.com/thomasloven/lovelace-slider-entity-row/blob/master/slider-entity-row.js) as RAW and saved it as slider-entity-row.js file in the folder /config/www/plugins.

After that I put the following under Resources: /config/www/plugins/slider-entity-row.js

Then tried the following code:

```
type: entities
entities:
  - light.bed_light
  - type: custom:slider-entity-row
    entity: light.kitchen_lights
```

Result... does not work! :-(

```
Custom element doesn't exist: slider-entity-row.
type: custom:slider-entity-row
entity: light.kitchen_lights
```

What could be the error?
