### ISSUE TITLE
Cover icon color not changing with state

### ISSUE THREAD

**Issue by CZonin** [thomasloven/lovelace-slider-entity-row#242]
My Home Assistant version: 2022.3.5

My lovelace configuration method (GUI or yaml):
yaml

What I am doing:
Card with light and cover slider entities.

What I expected to happen:
Both light and cover entity icons will change color based on state.

What happened instead:
Only light entity icon colors change based on state.

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
Where is the code?

**Comment by CZonin** [comment]
Sorry meant to add it.

```
type: custom:vertical-stack-in-card
cards:
  - type: entities
    title: Main Areas
    entities:
      - type: divider
        style:
          width: 107%
          height: 2px
          margin-left: '-16px'
          margin-right: auto
          opacity: 0%
      - type: custom:slider-entity-row
        entity: light.living_room_light
        name: Living Room
        toggle: false
        hide_state: true
        tap_action:
          action: toggle
      - type: custom:slider-entity-row
        entity: light.dining_area_light
        name: Dining Area
        toggle: false
        hide_state: true
        tap_action:
          action: toggle
      - type: custom:slider-entity-row
        entity: light.kitchen_lights
        name: Kitchen
        toggle: false
        hide_state: true
        tap_action:
          action: toggle
      - type: custom:slider-entity-row
        entity: light.upstairs_hallway_light
        name: Upstairs Hallway
        toggle: false
        hide_state: true
        tap_action:
          action: toggle
      - type: custom:slider-entity-row
        entity: light.den_lights
        name: Den
        toggle: false
        hide_state: true
        tap_action:
          action: toggle
      - type: divider
        style:
          background: '#121212'
          width: 112%
          height: 2px
          margin-left: '-16px'
          margin-top: 15px
          margin-right: 0px
          margin-bottom: 15px
          opacity: 100%
      - type: custom:slider-entity-row
        entity: cover.dining_area
        name: Dining Area
        icon: mdi:window-closed
        toggle: false
        hide_state: true
        tap_action:
          action: toggle
      - type: custom:slider-entity-row
        entity: cover.seventeen
        name: Kitchen
        icon: mdi:window-closed
        toggle: false
        hide_state: true
        tap_action:
          action: toggle
      - type: divider
        style:
          background: '#121212'
          width: 112%
          height: 2px
          margin-left: '-16px'
          margin-top: 15px
          margin-right: 0px
          opacity: 100%
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        entity: scene.movie
        tap_action:
          haptic: medium
          action: call-service
          service: scene.turn_on
          service_data:
            entity_id: scene.movie
        styles:
          card:
            - font-size: 12px
            - font-weight: regular
            - padding: 0px 10px 20px 10px
            - box-shadow: none
          icon:
            - width: 25px
            - margin-bottom: 12px
            - color: '#878E96'
      - type: custom:button-card
        entity: light.main_lights
        name: 15%
        icon: mdi:brightness-4
        tap_action:
          haptic: medium
          action: call-service
          service: light.turn_on
          service_data:
            entity_id: light.main_lights
            brightness_pct: 15
        styles:
          card:
            - font-size: 12px
            - font-weight: regular
            - padding: 0px 10px 20px 10px
            - box-shadow: none
          icon:
            - width: 25px
            - margin-bottom: 12px
            - color: '#878E96'
      - type: custom:button-card
        entity: light.main_lights
        icon: mdi:brightness-6
        name: 50%
        tap_action:
          haptic: medium
          action: call-service
          service: light.turn_on
          service_data:
            entity_id: light.main_lights
            brightness_pct: 50
        styles:
          card:
            - font-size: 12px
            - font-weight: regular
            - padding: 0px 10px 20px 10px
            - box-shadow: none
          icon:
            - width: 25px
            - margin-bottom: 12px
            - color: '#878E96'
      - type: custom:button-card
        entity: light.main_lights
        name: 100%
        icon: mdi:brightness-7
        tap_action:
          haptic: medium
          action: call-service
          service: light.turn_on
          service_data:
            entity_id: light.main_lights
            brightness_pct: 100
        styles:
          card:
            - font-size: 12px
            - font-weight: regular
            - padding: 0px 10px 20px 10px
            - box-shadow: none
          icon:
            - width: 25px
            - margin-bottom: 12px
            - color: '#878E96'

```
