### ISSUE TITLE
New Feature: Allow for icon: none

### ISSUE THREAD

**Issue by jgclark** [thomasloven/lovelace-slider-entity-row#245]
Requesting a new feature.

My Home Assistant version: 2022.3.7
My lovelace configuration method (GUI or yaml): yaml
What I am doing: trying to hide icon _without using full_row_
What I expected to happen: set `icon: none` and the text would start at the left
What happened instead:
<img width="380" alt="Screenshot 2022-03-27 at 13 20 34" src="https://user-images.githubusercontent.com/1671754/160281086-1230a526-c159-4a43-9ac3-603a1f9bdad3.png">

**Minimal** steps to reproduce:

```yaml
type: entities
entities:
  - type: custom:slider-entity-row
    entity: light.study_spots_zha_group_0x0003
    attribue: color_temp
    name: Brightness
    icon: none
state_color: true
```

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
