### ISSUE TITLE
Certain Entities Won't Show at All

### ISSUE THREAD

**Issue by davispeden1** [thomasloven/lovelace-slider-entity-row#246]
Environment:

> HA Core Version:  2022.4.1
> HASS OS 7.6
> Running on RPI 4
> slider-entity-row version 17.2.1

Issue:

- Certain entities no longer show at all.
- Some entities do not show the slider until the toggle is flipped on (not obeying default hide_when_off=false or obeying an explicit hide_when_off=false)

Card (with missing rows):
Note that I am missing rows for "Couch Lamp", and "Fan"
![image](https://user-images.githubusercontent.com/57494200/162462164-2e7da22d-84b6-4094-bc7f-45b9721e8f45.png)

YAML Config:
```
entities:
  - label: Lamps
    type: section
  - entity: switch.master_right_lamp
    icon: mdi:lamp
    name: Right Lamp
  - entity: switch.master_left_lamp
    icon: mdi:lamp
    name: Left Lamp
  - entity: switch.shelf_light
    icon: mdi:light-recessed
  - entity: light.master_bedroom_couch_lamp_dimmer
    name: Couch Lamp
    toggle: true
    icon: mdi:lamp
    type: custom:slider-entity-row
  - type: divider
  - entity: fan.master_fan
    name: Fan
    toggle: true
    icon: mdi:ceiling-fan
    type: custom:slider-entity-row
    hide_when_off: false
  - entity: switch.peloton_fan
    icon: mdi:fan
    name: Peloton Fan
show_header_toggle: false
title: Master Bedroom
type: entities
state_color: true
```
Here is another example where I have both a Fan missing and the slider on the Left Lamp isn's showing despite the hide_when_off being explicitly set to false:

Card displaying with issues:
![image](https://user-images.githubusercontent.com/57494200/162463523-85b71d8c-224a-4b9f-bc0c-c34e95f233b2.png)

YAML:
```
entities:
  - entity: light.den_lights
    name: Overhead Lights
    icon: mdi:light-recessed
    toggle: true
    type: custom:slider-entity-row
  - entity: light.den_right_lamp
    icon: mdi:floor-lamp
    name: Right Lamp
    toggle: true
    type: custom:slider-entity-row
  - entity: light.den_left_lamp
    icon: mdi:floor-lamp
    name: Left Lamp
    toggle: true
    type: custom:slider-entity-row
    hide_when_off: false
  - entity: fan.den_fan
    name: Fan
    toggle: true
    type: custom:slider-entity-row
    icon: mdi:ceiling-fan
show_header_toggle: false
title: Den
type: entities
state_color: true
```
