### ISSUE TITLE
null is not an object (evaluating 'this.parentElement.clientWidth')

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-slider-entity-row#247]
My Home Assistant version: 2022.5.0.dev20220414

My lovelace configuration method (GUI or yaml): Yaml

What I am doing:

Listing light groups in an auto-entities entities card

when I list all light.groups explicitly this does not happen. 

Is slider-entity-row not supported in auto-entities entities card then? the card shows perfectly fine, so I stumbled upon this error by accident..

related to #212 ?

What I expected to happen:

no error in inspector

What happened instead:

see below

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
  - type: custom:auto-entities
    card:
      type: entities
      title: Light groups auto
    filter:
      include:
        - domain: light
          attributes:
            entity_id: '$$*'
          options:
            type: custom:slider-entity-row
            toggle: true
          sort:
            method: state
            reverse: true
# End of code
```

Error messages from the browser console:
```
Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'this.parentElement.clientWidth')
```

<img width="1145" alt="Schermafbeelding 2022-04-14 om 07 48 20" src="https://user-images.githubusercontent.com/33354141/163322817-80b605c1-7d21-46de-9099-9e484512b8db.png">
**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
A smaller MWE:
```
type: custom:auto-entities
card:
  type: entities
  title: auto + slider-entity-row
filter:
  include:
    - entity_id: input_number.test_level_*
      options:
        type: custom:slider-entity-row
```
![image](https://user-images.githubusercontent.com/71872483/163475729-942b3a2e-81dd-46d6-b3d0-53c5e8016358.png)

![image](https://user-images.githubusercontent.com/71872483/163475913-365baa97-ca91-46a1-8a5f-7b78acfd3daf.png)
