### ISSUE TITLE
Slider-entity-row doesn't work any more for fan

### ISSUE THREAD

**Issue by SeByDocKy** [thomasloven/lovelace-slider-entity-row#248]
My Home Assistant version: 0.XXX.X

2022.4.4
My lovelace configuration method (GUI or yaml):

GUI/ lovelace-slider-entity-row  17.1.0

What I am doing:

What I expected to happen:

The slider is no more appearing ...

What happened instead:
Nothing shown

**Minimal** steps to reproduce:

```yaml
type: entities
entities:
  - entity: fan.geothermie_soufflerie
    name: Soufflerie
    show_state: true
    type: custom:slider-entity-row
show_header_toggle: false
state_color: true
title: Soufflerie

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [] Have made sure I am using the latest version of the plugin.
- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
