### ISSUE TITLE
Custom element doesn't exist

### ISSUE THREAD

**Issue by Emeraude998** [thomasloven/lovelace-slider-entity-row#250]
My Home Assistant version: 2022.5.2

My lovelace configuration method (GUI or yaml): GUI & yaml

What I am doing: Trying to get a slider UI element

What I expected to happen: A slider appearing on my dashboard

What happened instead: An error stating that the custom element doesn't exist

**Minimal** steps to reproduce:

Install plugin via HACS

Modified the URL of the ressources as stipulated in Step 3 Substep 6 of the manual guide

![image](https://user-images.githubusercontent.com/70350808/167318400-c1c4cea9-8973-4940-b8b5-00588fb56717.png)

Refreshed the browser cache

Created a new Entity card in dashboard
```yaml
# The least ammount of code possible to reproduce my error
type: entities
entities:
  - light.lumiere_chambre
  - type: custom:slider-entity-row
    entity: light.lumiere_chambre
# End of code
```

Error messages from the browser console:
![image](https://user-images.githubusercontent.com/70350808/167318376-cb12116c-7159-4324-b3db-4c2b48043344.png)

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
