### ISSUE TITLE
show_icon flag doesn't work

### ISSUE THREAD

**Issue by adabelleleiram** [thomasloven/lovelace-slider-entity-row#267]
My Home Assistant version: 2023.1.0

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
I used the full_row and show_icon flags (both set to true) but no icon was visible

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
  - type: custom:slider-entity-row
    entity: input_number.moon_light_phase
    full_row: true
    show_icon: true
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
