### ISSUE TITLE
No entity specified

### ISSUE THREAD

**Issue by RanAkiva** [thomasloven/lovelace-slider-entity-row#268]
My Home Assistant version: 
Home Assistant 2022.12.9
Supervisor 2022.12.1
Operating System 9.4

My lovelace configuration method (GUI or yaml): GUI 

What I am doing:
Installed slider-entity-row with hacs.
I want to add slider to brightness control of light.

What I expected to happen:
add slider.

What happened instead:
No slider.

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

type: entities
entities:
  - type: custom:slider-entity-row
  - entity: light.yeelight_ceiling1_0x7c57c60

# End of code
```

Error messages from the browser console:
No entity specified.
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
![No entity specified](https://user-images.githubusercontent.com/98401321/213136871-5c6332d0-a96a-4661-b253-883b274d4f74.JPG)

**Comment by thomasloven** [comment]
Check the example again. 

You have two entries. One is a slider entity row, the other has an entity.

Also
http://thomasloven.com/blog/2018/08/YAML-For-Nonprogrammers/

**Comment by RanAkiva** [comment]
Dear Thomas, 
Thank you for the quick replay. 

I don't have any program experience and I followed you example from the readme.md

type: entities
entities:
  - light.bed_light
  - type: custom:slider-entity-row
    entity: light.kitchen_lights

Just replaced the  entity: 
light.kitchen_lights with  
light.yeelight_ceiling1_0x7c57c60

And didn't use the first one: light.bed_light.

Can you help me?
I really don't know what to do.

Best, 
Ran Akiva

**Comment by thomasloven** [comment]
```yaml
type: entities
entities:
  - light.bed_light
  - type: custom:slider-entity-row
    entity: light.kitchen_lights
```

```yaml
type: entities
entities:
  - type: custom:slider-entity-row
  - entity: light.yeelight_ceiling1_0x7c57c60
```
