### ISSUE TITLE
percentage is disappeared, but only on my mobile device

### ISSUE THREAD

**Issue by RanAkiva** [thomasloven/lovelace-slider-entity-row#269]
My Home Assistant version:
Home Assistant 2022.12.9
Supervisor 2022.12.1
Operating System 9.4

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Installed slider-entity-row with hacs.
Slider on my pc is showing perfect.
However, percentage is disappeared, but only on my mobile device (android) Samsung.

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

type: entities
entities:
  - type: custom:slider-entity-row
    entity: light.yeelight_ceiling1_0x7c57c60

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
