### ISSUE TITLE
MQTT climate slider is not correct if min/max_temp are configured

### ISSUE THREAD

**Issue by HelgeBoehme** [thomasloven/lovelace-slider-entity-row#271]
My Home Assistant version: 2023.3.1
Frontend 20230302.0 - latest
slider-entity-row: 17.3.0

My lovelace configuration method (GUI or yaml): both

What I am doing:
I created integration from https://www.home-assistant.io/integrations/climate.mqtt/ and configured min and max_temp and step (in my case 7.5, 25 and 0.5).
Then I added custom:slider-entity-row using that climate entity.

What I expected to happen:
Slider swings between min and max value with configured step. On mouse-button-release, new value is submitted to entity.

What happened instead:
Slider always jumps to max value +1 (26 in my case). Moving slider only shows integer value changes. After mouse-button-release, slider jumps back to max value. The max value (25) is submitted to the entity regardless from position of release.
If I remove min/max_temp from the config, I can use the slider with the default range at integer steps.

For comparison I created input-number with the same range and step. Here everything works as expected.

**Minimal** steps to reproduce:

```yaml
mqtt:
  climate:
    - name: Heizung Wohnzimmer
      object_id: comet_wohnzimmer
      unique_id: climate.comet_wohnzimmer
      temperature_unit: C
      initial: 7.5
      min_temp: 7.5
      max_temp: 25.0
      precision: 0.5
      temp_step: 0.5
[...]
input_number:
  comet_wohnzimmer_temp_set:
    name: Heizung Wohnzimmer
    min: 7.5
    max: 25
    step: 0.5
    unit_of_measurement: °C
    icon: mdi:thermometer
```

```yaml
    cards:
      - type: entities
        entities:
          - entity: climate.comet_wohnzimmer
            type: custom:slider-entity-row
          - entity: input_number.comet_wohnzimmer_temp_set
            type: custom:slider-entity-row
```

![image](https://user-images.githubusercontent.com/16921350/226409305-02ea7f7d-5372-4a7a-ac2a-9f89d8589e57.png)

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
