### ISSUE TITLE
"off" word disappeared from light slider after latest HACS or HA update

### ISSUE THREAD

**Issue by BaltasarParreira** [thomasloven/lovelace-slider-entity-row#272]
My Home Assistant version: 
Home Assistant 2023.4.3
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230411.0 - latest

My lovelace configuration method (GUI or yaml):

<html>
<body>
<h2 id="title" class="mdc-dialog__title" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-headline6-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-headline6-font-size, 1.25rem); line-height: var(--mdc-typography-headline6-line-height, 2rem); font-weight: var(--mdc-typography-headline6-font-weight, 500); letter-spacing: var(--mdc-typography-headline6-letter-spacing, 0.0125em); text-decoration: var(--mdc-typography-headline6-text-decoration, inherit); text-transform: var(--mdc-typography-headline6-text-transform, inherit); display: block; position: relative; flex-shrink: 0; box-sizing: border-box; margin: 0px 0px 1px; padding: 24px 24px 0px; color: var(--mdc-dialog-heading-ink-color, rgba(0, 0, 0, 0.87));">Home Assistant Community Store</h2><div id="content" class="mdc-dialog__content" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-body1-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: 14px; line-height: var(--mdc-typography-body1-line-height, 1.5rem); font-weight: 400; letter-spacing: var(--mdc-typography-body1-letter-spacing, 0.03125em); text-decoration-line: ; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-transform: none; flex-grow: 1; box-sizing: border-box; margin: 0px; overflow: auto; color: rgb(225, 225, 225); padding: var(--dialog-content-padding, 24px); position: var(--dialog-content-position, relative); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><slot id="contentSlot" style="margin-top: 0px; margin-bottom: 0px;"><div><p class="" style="margin: 0px; color: var(--primary-text-color);"><div class="markdown-body" style="text-size-adjust: 100%; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; line-height: 1.5; overflow-wrap: break-word;">

Integration version: | 1.32.1
-- | --
Frontend version: | 20220906112053
Repositories: | 1270
Downloaded repositories: | 10

</div></p></div></slot></div>
</body>
</html>

![image](https://user-images.githubusercontent.com/1650425/231771677-d9b8a048-efec-41c7-a434-bc19760e4e53.png)

What I am doing:

What I expected to happen:
Slider with OFF in the end when brightness is 0

What happened instead:
The "off" word disappeared when brightness is 0

![image](https://user-images.githubusercontent.com/1650425/231770957-ba79ba77-f914-4066-8de1-34c5448cefcf.png)

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
type: horizontal-stack
cards:
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - type: custom:slider-entity-row
            entity: light.canal2
            step: 1
            icon: mdi:ceiling-light-multiple
            hide_state: false
          - type: custom:slider-entity-row
            entity: light.canal1
            step: 1
            icon: mdi:ceiling-light-multiple
            hide_state: false
        show_header_toggle: false

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
