### ISSUE TITLE
When covers position is 100% the percentage disappeared

### ISSUE THREAD

**Issue by MiguelCosta** [thomasloven/lovelace-slider-entity-row#273]
My Home Assistant version: 2023.6.1

What I expected to happen:

![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/645482/6c62a574-34ae-4dd3-b0d8-a6f76b3231e0)

**Minimal** steps to reproduce:

```yaml
      - entity: cover.estore_quarto_1
        full_row: false
        name: Posição
        secondary_info: last-changed
        type: custom:slider-entity-row
        step: 5
        hide_state: false
        grow: true
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
