### ISSUE TITLE
Full_Row is not working

### ISSUE THREAD

**Issue by countblackjack** [thomasloven/lovelace-slider-entity-row#278]
My Home Assistant version:
Home Assistant 2023.9.2
Frontend 20230911.0 - latest

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Adding the slider to a picture elements card
What I expected to happen: full width slider
What happened instead: slider stayed same size as without the full width option

```yaml
type: picture-elements
image: http://192.168.1.82:8123/local/210220.jpg
elements:
  - type: custom:slider-entity-row
    entity: light.ground_floor_living_areas
    full_row: true
    style:
      left: 50%
      top: 95%
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
> Adding the slider to a picture elements card

Not supposed to be used here.
It is supposed to be used inside Entities card.

**Comment by countblackjack** [comment]
Thank you, I'll find another solution.On Sep 19, 2023 23:27, ildar170975 ***@***.***> wrote:

Adding the slider to a picture elements card

Not supposed to be used here.
It is supposed to be used inside Entities card.

**Comment by thomasloven** [comment]
```yaml
type: custom:slider-entity-row
entity: light.bed_light
full_row: true
style:
  left: 50%
  top: 50%
  width: 100%
```
