### ISSUE TITLE
Value Balloon not showing in 2023.11

### ISSUE THREAD

**Issue by gnsa14** [thomasloven/lovelace-slider-entity-row#279]
My Home Assistant version: Core-2023.11.0, Supervisor-2023.10.1, OS-11.1, Frontend-20231030.1

My lovelace configuration method (GUI or yaml): Yaml

What I am doing: full width slider in tile

What I expected to happen: when sliding the bubble above slider position shows value

What happened instead: bubble not showing, hence I don't know what value is at new slider position. Was showing in previous HASS build

**Minimal** steps to reproduce: -

Example of a normal slider bubble, which still works in 2023.11
![bubble](https://github.com/thomasloven/lovelace-slider-entity-row/assets/87852467/d4e32ef2-66b4-4e56-b4b6-797db41155a9)

```yaml
# The least ammount of code possible to reproduce my error

- type: entities
  entities:
    - type: custom:slider-entity-row
      entity: input_number.manual_grid_sp
      full_row: true
      hide_state: true
    - entity: input_select.grid_sp_control

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
