### ISSUE TITLE
Slider not avaiable on iOS in 2023.11

### ISSUE THREAD

**Issue by dapuzz** [thomasloven/lovelace-slider-entity-row#281]
Hi, just after upgrate to 2023.11 the slider is missing on my iPhone ( ios15)

I have 
In the log I can see this message every time I refresh the page:

```
2023-11-06 12:17:53.717 ERROR (MainThread) [frontend.js.latest.202310301] Uncaught error from WebKit 605.1.15 on iOS 15.5 TypeError: Cannot instantiate a custom element inside its own constructor during upgrades HTMLElement ([native code]::) 
construct ([native code]::)
y (src/scoped-custom-element-registry.js:173:6)
super (src/reactive-element.ts:930:4)
A (src/lit-element.ts:115:)
super (slider.ts:256:4)
_ (::)
F (src/components/ha-slider.ts:6:39)
c (src/scoped-custom-element-registry.js:390:8)
a (src/scoped-custom-element-registry.js:236:20)
```
The slider is correctly placed using desktop browser.
Is there any other action I can do to help with the issue?

---
- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins. (uplate ios section,   javascript_version: latest is no more valid)
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by BatmanKuhn** [comment]
Same here

**Comment by BatmanKuhn** [comment]
Not sure if this is the same issue. On my iPhone, the slider shows correctly but not visible on iPad (Both APPs are version 2023.7)

**Comment by FranciscoBigWings** [comment]
I have same error in iOS 16.3.1 (iPhone 12 pro max) after updating HA to 2023.11.1 and HAOS 11.1

Uncaught error from WebKit 605.1.15 on iOS 16.3.1 TypeError: Cannot instantiate a custom element inside its own constructor during upgrades HTMLElement ([native code]::) construct ([native code]::) y (src/scoped-custom-element-registry.js:173:6) super (src/reactive-element.ts:930:4) A (src/lit-element.ts:115:) super (slider.ts:256:4) _ (::) F (src/components/ha-slider.ts:6:39) c (src/scoped-custom-element-registry.js:390:8) a (src/scoped-custom-element-registry.js:236:20)

**Comment by GrizzlyAK** [comment]
I can confirm following update to 2023.11 that this no longer works on the HA iOS app on my iPhone 7 iOS 15.7.9. The sliders do not show at all. They appear fine on the Desktop (Win10, Firefox).

As an aside, my card-mod to turn these into a Hue Slider has failed as well, due to the apparent Front End coding changes and the disappearance of my keyed elements. I've made some progress fixing it by hacking some CSS together, but it isn't at its best. Read more about that topic starting [here](https://community.home-assistant.io/t/lovelace-custom-hue-slider/369839/14) onward.

Though getting this working on iOS is a priority.

**Comment by ildar170975** [comment]
iPad Air 2 (iOS 15.x) - slider not displayed:

![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/71872483/68db9a56-40d8-47bf-a7b5-e377c96dbf23)

Chrome + Win10:

![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/71872483/2a6d3b22-bc7f-4750-8542-68b541e616e0)

**Comment by ildar170975** [comment]
This is not only about slider-entity-row.
A standard HA slider does not work in iOS too after 2023.11.

Custom slider slider-entity-row in Entities:
```
type: entities
title: custom:slider-entity-row
entities:
  - entity: input_number.test_number
    type: custom:slider-entity-row
```
iPad Air 2 (iOS 15.x) - slider not displayed:

![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/71872483/61a646e1-9dfc-40f1-8061-59f13752ea5f)

Chrome + Win10:

![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/71872483/444e9943-e738-438b-b042-1fee2261225f)

-----------

Standard slider in more-info:
iPad Air 2 (iOS 15.x) - slider not displayed:

![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/71872483/68db9a56-40d8-47bf-a7b5-e377c96dbf23)

Chrome + Win10:

![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/71872483/2a6d3b22-bc7f-4750-8542-68b541e616e0)

**Comment by FSHelgeland** [comment]
I do have the same on my iPad Air 2, is someone working on a fix? It works fine in all web browsers as well in Android and in newer ios versions. My iPad Air 2 is quite useless if it stays like this.

**Comment by 9840380** [comment]
same problem iphone 10 xs ios 14

**Comment by gcoan** [comment]
Interesting.  I'm NOT seeing the sliders on my iPad (IOS 12) on the companion app, but on my iPhone (IOS14) in the companion app they all appear fine.
Also fine in Windows 10 in the Edge Browser
HA 2023.11.2

**Comment by 3ative** [comment]
This has now been fixed - Check HACS for the update.

**Comment by gcoan** [comment]
I just installed slider-entity-row 17.4.0 from HACS, reloaded the browser and modified a dashboard to use the new control

```
          - type: horizontal-stack
            cards:
              - type: entities
                entities:
                  - entity: sensor.g_sd2237g182_soc
                  - entity: select.g_sd2237g182_mode
                  - entity: select.g_sd2237g182_force_charge
                  - type: custom:slider-entity-row
                    entity: number.g_sd2237g182_target_soc             
                  - entity: select.g_sd2237g182_charge_start_time_slot_1
                  - entity: select.g_sd2237g182_charge_end_time_slot_1
                  - entity: select.g_sd2237g182_temp_pause_charge
                  - type: custom:slider-entity-row
                    entity: number.g_sd2237g182_battery_charge_rate
                  - entity: select.g_sd2237g182_discharge_start_time_slot_1
                  - entity: select.g_sd2237g182_discharge_end_time_slot_1
                  - type: custom:slider-entity-row
                    entity: number.g_sd2237g182_battery_discharge_rate
                  - entity: number.g_sd2237g182_battery_power_reserve
                title: G182 Inv1 Control
```

unfortunately it doesn’t seem to work, still no sliders on my iPad

these entities are in a horizontal grid within a vertical grid if that is relevant?

![226AC10C-E3A2-4663-9CCC-0FEF9B767472](https://github.com/thomasloven/lovelace-slider-entity-row/assets/142018870/fb59f1a4-4487-44e3-aa29-0ef8ab8b957d)

**Comment by ildar170975** [comment]
1. Suggest you to test the slider-entity-row (any card) without any any other custom components to prevent interfering.
2. Clear a frontend cache on your Companion App after any update.

**Comment by thomasloven** [comment]
This has *not* been fixed by a slider-entity-row update.
I was starting to look at it, but my ipad air 2 was out of battery, so I couldn't reproduce the problem with any device I had available.

This is an issue with Home Assistant and cannot be fixed from here.

Please refer to https://github.com/home-assistant/frontend/issues/18600.
If you have any **NEW** information, please post that there.
If you are experiencing this problem, do **NOT** post a "me too" there. Give the original post a thumbs up instead.

**Comment by gcoan** [comment]
Here’s the yaml for a dedicated entities card on a new dashboard view:
```
  - title: Test
    path: test
    badges: []
    cards:
      - type: entities
        entities:
          - entity: number.g_sd2237g182_target_soc
          - type: custom:slider-entity-row
            entity: number.g_sd2237g182_target_soc
        title: Test entities
```

Neither the standard slider nor the slider-entity-row appear on my iPad
![8E22083D-6092-4067-8711-65B5BCBB27FE](https://github.com/thomasloven/lovelace-slider-entity-row/assets/142018870/b9b2e4f1-4b57-4425-8bf7-1762a55bd22a)

but are fine on my iPhone 
![B80BBF5C-256C-4434-A434-2FEC538E24EF](https://github.com/thomasloven/lovelace-slider-entity-row/assets/142018870/8b958c19-8ee6-4ea8-b3ff-d49af1e1f77a)
