### ISSUE TITLE
Sliding does not show slider value

### ISSUE THREAD

**Issue by JunghaJungha** [thomasloven/lovelace-slider-entity-row#283]
My Home Assistant version: 2023.11

My lovelace configuration method (GUI or yaml): yaml (via picture elements card)

What I am doing: Setting a new value via the slider does not show the actual slider value anymore.

What I expected to happen: When shifting the slider it should report the slider value, which will be the value when release the slider.

What happened instead: Now I have to guess the value, it used to work previously.

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
        - type: picture-elements       
          image: /local/ui/xxx.png
          elements:
                  - type: custom:slider-entity-row
                    entity: input_number.slidervalue
                    full_row: true
                    style: 
                        left: 50%
                        top: 90%
                        width: 60%
# End of code
```

Error messages from the browser console:
none
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
