### ISSUE TITLE
Sliders for multiple attributes per row

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [thomasloven/lovelace-slider-entity-row#284]
Hi,

I think it would be fabulous if this could show multiple attribute sliders per row.

For instance, a light could have sliders for both brightness _and_ colour temperature; a cover could have sliders for percent open _and_ slat angle; etc etc.

Would this be possible?

**Comment by thomasloven** [comment]
```yaml
type: entities
entities:
  - type: custom:slider-entity-row
    entity: ligh.bed_light
  - type: custom:slider-entity-row
    entity: light.bed_light
    attribute: hue
    name: Hue
    icon: " "
```

![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/1299821/87c99498-e73d-4fe5-9d3f-b76bf5e61653)
