### ISSUE TITLE
slider-entity-row has become extremely hard to use on HA iOS app

### ISSUE THREAD

**Issue by kenni** [thomasloven/lovelace-slider-entity-row#296]
My Home Assistant version:
2024.1.5.

My lovelace configuration method (GUI or yaml):
GUI and YAML.

What I am doing:
Trying to drag the slider on Home Assistant Companion (v2024.1) iOS app.

What I expected to happen:
The slider should move.

What happened instead:
The slider doesn't move in 50-80% of the attempts. I've tried to record a 1 minute video illustrating the issue. As I'm trying to record while performing the slides, the movement of my finger isn't 100% horizontal, but I would still expect it to work, as my vertial movement isn't enough to trigger vertical scrolling of the screen.

I've been using this exact configuration for around 2 years, and I believe this issue started at some point in 2023. I do not know if this is caused by a change in iOS, Home Assistant, the HA Companion app or slider-entity-row, but something has definitely changed for the worse. Setting "javascript_version: latest" in configuration.yaml as per the wiki, does not seem to change anything.

Link to video:
https://drive.google.com/file/d/1EiH38S8VsN7Y7RAhvIxPHmVihlgogY00/view?usp=sharing

**Minimal** steps to reproduce:

```yaml
type: entities
title: Rullegardiner - Stueplan
entities:
  - type: custom:slider-entity-row
    name: Kontorplads
    entity: cover.rollerblind_0001
  - type: custom:slider-entity-row
    name: Sofaplads
    entity: cover.rollerblind_0002
  - type: custom:slider-entity-row
    name: Spisestue syd 1
    entity: cover.rollerblind_0005
  - type: custom:slider-entity-row
    name: Spisestue syd 2
    entity: cover.rollerblind_0006
  - type: custom:slider-entity-row
    name: Spisestue vest
    entity: cover.rollerblind_0003
  - type: custom:slider-entity-row
    name: Udestuedør
    entity: cover.rollerblind_0007
  - type: custom:slider-entity-row
    name: Køkken vest
    entity: cover.rollerblind_000d
  - type: custom:slider-entity-row
    name: Køkken nord
    entity: cover.rollerblind_0009
  - type: custom:slider-entity-row
    name: Gæsteværelse
    entity: cover.rollerblind_0004
state_color: false
```

Setting "javascript_version: latest" in configuration.yaml does not seem to change anything:
```yaml
frontend:
  javascript_version: latest
```
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
