### ISSUE TITLE
rtl direction appears to be broken

### ISSUE THREAD

**Issue by RoboMagus** [thomasloven/lovelace-slider-entity-row#297]
My Home Assistant version: 2024.2.1
(I believe this was still working prior to the Feb update, but unsure)

My lovelace configuration method (GUI or yaml): Yaml

What I am doing: Inverting the render direction of a slider

What I expected to happen: The slider to show Right to Left. E.g.:
![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/68224306/29e946c5-9789-4051-8e6c-fff8e4077623)

What happened instead: It stays Left to Right

**Minimal** steps to reproduce:

```yaml
  - entity: cover.livingroom_curtain_front_right
    name: rechts
  - entity: cover.livingroom_curtain_front_right_inverted
    type: custom:slider-entity-row
    full_row: true
    hide_state: true
    step: 5
    dir: rtl
```

Error messages from the browser console:
None

Resulting HTML:
(Note that `dir` here states `ltr` instead of `rtl`)
```
<div class="wrapper">
      <!--?lit$654776852$-->
            <!--?lit$654776852$-->
            <ha-slider labeled="" pin="" ignore-bar-touch="" dir="ltr" class="full" role="presentation"></ha-slider>
      <!--?lit$654776852$-->
      <!--?lit$654776852$-->
</div>
```
![image](https://github.com/thomasloven/lovelace-slider-entity-row/assets/68224306/12200e49-bbba-4954-a7d7-720d9b850e89)

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
