### ISSUE TITLE
SWITCH: Action button not working for Call service

### ISSUE THREAD

**Issue by KirkKirk** [thomasloven/lovelace-slider-entity-row#302]
My Home Assistant version: 2024.7.1

My lovelace configuration method (GUI or yaml): GUI or yaml

What I am doing: Press the button

What I expected to happen: Toggle switch

What happened instead: Not toggle

**Minimal** steps to reproduce: Press multiple times

```yaml
type: custom:slider-button-card
entity: number.boiler_controler_set_power
show_state: true
slider:
  direction: left-right
  background: gradient
  use_state_color: true
  compact: true
  toggle_on_click: true
  use_percentage_bg_opacity: true
  show_track: true
  force_square: false
icon:
  icon: ''
  tap_action:
    action: none
  show: true
  use_state_color: true
show_attribute: false
show_name: true
compact: false
action_button:
  mode: custom
  show: true
  show_spinner: true
  tap_action:
    action: call-service
    service: switch.toggle
    target:
      entity_id: switch.boiler_controler_boiler_overide_switch
    data: {}

# End of code
```

Error messages from the browser console: Failed to call service switch/toggle. must contain at least one of entity_id, device_id, area_id, floor_id, label_id.

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
