### ISSUE TITLE
Default coloring of Cover icons does not work

### ISSUE THREAD

**Issue by ChrisMuki** [thomasloven/lovelace-slider-entity-row#305]
My Home Assistant version: 2024.10.3

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
i use this as entity in an entities card:
 - type: custom:slider-entity-row
    entity: cover.drbl_1_ch1_a_dusche_rolladen

What I expected to happen:
As the plain "entity: cover.drbl_1_ch1_a_dusche_rolladen" changes its color when not fully closed, i would exspect this also for the [custom clider enti](custom:slider-entity-row)

What happened instead:
Color does not change at all

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
type: entities
title: Dusche
entities:
  - entity: cover.drbl_1_ch1_a_dusche_rolladen
  - type: custom:slider-entity-row
    entity: cover.drbl_1_ch1_a_dusche_rolladen
show_header_toggle: false
state_color: true
# End of code
```

Error messages from the browser console:
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/a1097475-8331-4fdf-9508-defa83428a35">

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by dcapslock** [comment]
Issue if that the state_color is not bubbling down to the entity row. If you set state_color on the row then it works.

```
# The least ammount of code possible to reproduce my error
type: entities
title: Dusche
entities:
  - entity: cover.drbl_1_ch1_a_dusche_rolladen
  - type: custom:slider-entity-row
    entity: cover.drbl_1_ch1_a_dusche_rolladen
    state_color: true # <-- Add here to workaround issue
show_header_toggle: false
state_color: true
# End of code
```
