### ISSUE TITLE
hide_full_row_when_off?

### ISSUE THREAD

**Issue by capstan1** [thomasloven/lovelace-slider-entity-row#31]
Hi,
can there be a option to hide the full row when the entity is off? As full rows creates another line, hiding it is leaving a empty line at the moment.
**ON:**
![image](https://user-images.githubusercontent.com/17147867/54074194-cdae0080-428f-11e9-8f54-74fdbab1289a.png)
**OFF:**
![image](https://user-images.githubusercontent.com/17147867/54074199-e9190b80-428f-11e9-9e54-5ddaaaf2746e.png)

Ideally the line would dissapear when using full row.

Note: obviously it wont work in my example because I've been using entity-fold here. Just think of it without the small arrows 😉

**Comment by MightyMilster** [comment]
I am having this same issue.

Im running HA 0.89.1 and just updated my card to the latest version (4bc787). That last update seems to leave blank canvas where the slider would be, had the entity been available. It wasn't an issue on f854da.

See below, Shed Light 1 and 2 have sliders.

![space](https://user-images.githubusercontent.com/43132848/54078695-fe8a4600-4320-11e9-8207-55e1f0b346ab.jpg)

**Comment by thomasloven** [comment]
I never liked `hide_when_off` because what if you want to turn on the light, but not have it be the same brightness as it was when you turned it off?

Also, if there was an entire card of only sliders, it could (almost) disappear from the view, which would be confusing to the user and mess with the layouting engine.

**Comment by capstan1** [comment]
Thanks for your answer! I get your idea, but why don't give us the option? I'm just trying to get towards a more simple and elegant look which hides elements when they aren't necessary (for me).

Thanks for all your addons btw!

**Comment by thomasloven** [comment]
Because if I make it an option it goes from being an unintended side effect or even a bug to being a feature which I must maintain, test and guarantee functionality of in all future releases.

I'm not saying I won't. I'm just saying I need to think it through properly.

**Comment by MightyMilster** [comment]
I understand now.
From my example, Shed Light 1 is a sonoff that controls power to the lamp socket circuit. Shed Dimmer 1 (which you can't see) is a Wemo smart-bulb; so a separate entity. Obviously quite dead when the power is off. If I set `hide_when_off = false` I can not change the slider value in a lasting way because the entity is not there to receive the value. So, in my situation it does not align with your comment about wanting a different setting the next time yuo want a light on. But I can see how that would be useful to other users. 
Further; one would need to consider whether an admin that has created a card full of sliders would actually prefer that the card shrinks to a almost gone card.
I really hope you maintain `hide_when_off`; I love what it does for teh look of my front end.
Not trying to complicate things but are the following possible options...
`hide_when_unavailable` hide if the entity is unavailable, but I am not sure if that can be assessed differently to off
`remove_when_off` hide leaves the blank canvas; whereas 'remove_when_off' hides + removes the canvas line-space.
PS. I will thumbs up your last comment as a vote for further maintenance :)

**Comment by thomasloven** [comment]
Come to think of it, this can be done with [auto-entities](https://github.com/thomasloven/lovelace-auto-entities) or [entity-filter](https://www.home-assistant.io/lovelace/entity-filter/)

**Comment by maniscalcojohn** [comment]
Was this behavior recently changed in an update? Until recently the full row would completely disappear and the gap would close up. Now it says "off." Having the full row is nice for some of the long names, especially when viewed on smaller screens. 

```
entities:
  - entity: light.living_room_lights
  - entity: light.living_room_lights
    full_row: true
    hide_when_off: true
    type: 'custom:slider-entity-row'
  - entity: light.fan_light
  - entity: light.fan_light
    full_row: true
    hide_when_off: true
    type: 'custom:slider-entity-row'
  - entity: light.entry_light
  - entity: light.entry_light
    full_row: true
    hide_when_off: true
    type: 'custom:slider-entity-row'
  - entity: light.dining_room_lights
  - entity: light.dining_room_lights
    full_row: true
    hide_when_off: true
    type: 'custom:slider-entity-row'
  - entity: light.dining_table_light
  - entity: light.dining_table_light
    full_row: true
    hide_when_off: true
    type: 'custom:slider-entity-row'
  - entity: fan.fan
    type: 'custom:custom-fan-card'
show_header_toggle: true
title: Living Room
type: entities
```

![Capture](https://user-images.githubusercontent.com/29788996/71484738-933c3280-27d3-11ea-831b-4c8cb61fc7ec.JPG)
