### ISSUE TITLE
hide_when_off has no effect on a media player

### ISSUE THREAD

**Issue by thermseekr** [thomasloven/lovelace-slider-entity-row#32]
Option hide_when_off has no effect on a media player.

Media player on:

<img width="447" alt="Captura de Tela 2019-03-09 às 20 49 35" src="https://user-images.githubusercontent.com/48183960/54078775-09a38e80-42ad-11e9-9601-52c333350503.png">

Media player off:

<img width="443" alt="Captura de Tela 2019-03-09 às 20 49 58" src="https://user-images.githubusercontent.com/48183960/54078781-1e802200-42ad-11e9-8ea7-a2e479678b4c.png">

ui-lovelace.yaml:

```
- type: vertical-stack
  cards:
  - type: media-control
    entity: media_player.denon_sala
  - type: custom:slider-entity-row
    entity: media_player.denon_sala
    hide_when_off: true
```
