### ISSUE TITLE
cover tilt-position?

### ISSUE THREAD

**Issue by bruxy70** [thomasloven/lovelace-slider-entity-row#38]
I use the slider entity row to show and control the cover position. How do I make another one to show the tilt-position?

```
      - type: entities
        entities:
        - entity: cover.gallery_left
        - type: custom:slider-entity-row
          entity: cover.gallery_left
          full_row: true

```
