### ISSUE TITLE
Home Assistant 0.92.x: Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by thecode** [thomasloven/lovelace-slider-entity-row#45]
After update to Home Assistant 0.92.0 / 0.92.1 the error appears every time an entity with the custom slider is accessed via the UI.

lovelace card configuration:
```
entities:
  - entity: light.living_room_tv_leds
    type: 'custom:slider-entity-row'
title: Living Room
type: entities
```

Full error:
`019-04-27 23:18:55 ERROR (MainThread) [frontend.js.es5.201904240] https://####.###/frontend_es5/app.0d431883.js:2:79851 Uncaught TypeError: Cannot convert undefined or null to object`

Tried to empty cache and hard reload.

**Comment by thomasloven** [comment]
Could you try opening `slider-entity-row.js` in any editor and just saving it again without any changes?

**Comment by thecode** [comment]
Done, still get the same error, I also noticed the error appears for all sliders (covers also, not only light)

`2019-04-29 23:18:52 ERROR (MainThread) https://####.###/frontend_es5/app.0d431883.js:2:79851 Uncaught TypeError: Cannot convert undefined or null to object`

**Comment by thecode** [comment]
I looked at the error more closlely with Chrome DevTools:

`Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at HTMLElement._listenKeyEventListeners (app.0d431883.js:2)
    at HTMLElement.attached (app.0d431883.js:2)
    at HTMLElement.value (app.0d431883.js:2)`

Maybe this can help

**Comment by GeekRuthie** [comment]
I'm having the same error, on a new install of 0.92.1. Please let me know if there's anything I can do to help unravel the mystery.

**Comment by ronendayan** [comment]
Same here
using lovelace, HA 0.92.1
Trying to call service frontend.set_theme
`2019-05-15 08:27:32 ERROR (MainThread) [frontend.js.latest.201904240] https://xxx.xxx.xxx/frontend_latest/app.7ac4ac3c.js:2:60391 Uncaught TypeError: Cannot convert undefined or null to object`

**Comment by thomasloven** [comment]
Please let me know if this is still a problem with version v0.1

**Comment by thecode** [comment]
Still get the same error on two setups, I'm going to try only this module on fresh install to try to understand what is causing the error.

**Comment by tuan280195** [comment]
+1

**Comment by thomasloven** [comment]
Could you please make sure the light is turned on and then go go `/dev-state`, find the entity in the list and copy the contents of the rightmost column for it and paste here?

**Comment by tuan280195** [comment]
> Could you please make sure the light is turned on and then go go `/dev-state`, find the entity in the list and copy the contents of the rightmost column for it and paste here?


switch.fan | on | friendly_name: FAN icon: mdi:asterisk
-- | -- | --
switch.light | on | friendly_name: Extra Light
switch.main_light | on | friendly_name: Main light
switch.pc | on | friendly_name: My Room PC icon: mdi:desktop-classic

**Comment by thecode** [comment]
I get the same error both for lights and covers.
Light:

light.living_room_tv_leds | on | effect_list: Off,Meteor Shower,Gradual Change,Breath,Flash,On/Off Gradual,Red/Green Change brightness: 255 hs_color: 300,100 rgb_color: 255,0,255 xy_color: 0.385,0.155 white_value: 32 effect: Off friendly_name: Living Room TV LEDs supported_features: 189
-- | -- | --

Cover:

cover.living_room_1 | open | current_position: 91 friendly_name: Living Room 1 supported_features: 15
-- | -- | --

**Comment by thecode** [comment]
I performed a clean Home Assistant Installation (v0.94.4).
Added only a cover component, checked it for a day without any errors.
After adding the slider-entity-row, error started to appear in logs.

Here is the complete lovelace test config:
```
title: Home
resources:
  - url: /local/plugins/slider-entity-row.js?v=0.2
    type: module
views:
  - cards:
      - entities:
          - type: 'custom:slider-entity-row'
            entity: cover.shelly_shsw_21_9f5ef1
            name: Parents Room Shutter
        type: entities
    badges: []
    path: default_view
    title: Home
```

![image](https://user-images.githubusercontent.com/1858925/60011274-1b554a00-9682-11e9-8f35-a7f9b51d9db4.png)

Error:
`http://*.*.*.*:8123/frontend_latest/app.29ef27ad.js:2:59869 Uncaught TypeError: Cannot convert undefined or null to object `

Thank you for the effort, if there is something more I can do to test let me know.

**Comment by thecode** [comment]
I performed a clean Home Assistant Installation (v0.94.4).
Added only a cover component, checked it for a day without any errors.
After adding the slider-entity-row, error started to appear in logs.

Here is the complete lovelace test config:
```
title: Home
resources:
  - url: /local/plugins/slider-entity-row.js?v=0.2
    type: module
views:
  - cards:
      - entities:
          - type: 'custom:slider-entity-row'
            entity: cover.shelly_shsw_21_aa5bb1
            name: Parents Room Shutter
        type: entities
    badges: []
    path: default_view
    title: Home
```

![image](https://user-images.githubusercontent.com/1858925/60011274-1b554a00-9682-11e9-8f35-a7f9b51d9db4.png)

Error:
`http://*.*.*.*:8123/frontend_latest/app.29ef27ad.js:2:59869 Uncaught TypeError: Cannot convert undefined or null to object `

Thank you for the effort, if there is something more I can do to test let me know.
