### ISSUE TITLE
Full row not working inside pop-up card?

### ISSUE THREAD

**Issue by martikainen87** [thomasloven/lovelace-slider-entity-row#47]
I'm not sure if this should work or not, but i've been trying to apply the full row feature inside my popup-cards to create a nice mobile GUI. 

When adding the full row to the entities it won't hide the name. 
The second issue is that the 'show_header_toggle: false' wont do anything. So I'm guessing this is not implemented to work inside the popup-cards so maybe this is more of a feature request? :) 

Here's a snippet of a popup-card when opened, as you can see the slider is in between the name and the toggle switch.  

![full_row](https://user-images.githubusercontent.com/26088869/57255462-1c8bd280-7054-11e9-944c-fffcadf46b0c.PNG)

Code: (As you'll see I cut out a bit of code that was above the actual functions not working)
```
popup_cards:
  light.sovrum:
    title: Sovrum
    card:
      type: vertical-stack
      cards:
        - type: entities
          show_header_toggle: false
          entities:
            - type: custom:slider-entity-row
              entity: light.sovrum_tak_1
              full_row: true
              name: Taklampa
```

Or am I just doing something wrong in the code? I've been playing around with the code alot and so I might just be a bit blind :)
