### ISSUE TITLE
Light dimmer value is off by 1%

### ISSUE THREAD

**Issue by Hypfer** [thomasloven/lovelace-slider-entity-row#50]
![image](https://user-images.githubusercontent.com/974410/58386323-45bdd400-7ffe-11e9-99bc-b24709815737.png)

```
entities:
  - text: Beleuchtung
    type: 'custom:text-divider-row'
  - entity: light.light_31
    name: Decke
    type: 'custom:slider-entity-row'
  - entity: light.couchtisch
    name: Couchtisch
    type: 'custom:slider-entity-row'
  - entity: light.ledoors
    name: LEDoors
    type: 'custom:slider-entity-row'
  - entity: light.light_29
    name: Sideboard
    type: 'custom:slider-entity-row'
  - entity: light.playbar_schreibtisch
    name: Playbar
    type: 'custom:slider-entity-row'
  - text: Schalter
    type: 'custom:text-divider-row'
type: entities
```
