### ISSUE TITLE
Slider not visible with deconz lights

### ISSUE THREAD

**Issue by AnthonMS** [thomasloven/lovelace-slider-entity-row#58]
My Home Assistant version: 0.96.5

My lovelace configuration method (GUI or yaml): YAML

What I am doing: I am trying to get the slider to show for my light groups and zigbee lights connected through deconz.

What I expected to happen: I set up deconz and connected all my zigbee lights to that instead of the bridges. And expected the slider would still work, as it is the same lights as I used through hue bridge, where the slider had no problems. I have alos tried creating light groups, but that does not do anything, there is still no slider.

What happened instead: After I set up the lights through deconz, the slider does not show when turning on the lights. Like it did before. It still work for my mqtt lights. Toggle switch still works and clicking the entity still shows the more-info pop-up.

**Minimal** steps to reproduce: Connect a hue bulb to deconz and integrate that into HA. Then make the entity like the yaml below.
The slider will not show, like it does if I make the completely same entity setup, but with a mqtt light.

```yaml
# The least ammount of code possible to reproduce my error

      - type: custom:slider-entity-row
        entity: light.deconz_light
        name: Bedroom
        toggle: true
        hide_when_off: true

# End of code
```

Error messages from the browser console: No errors show, the lights still turn on/off with the toggle and I can still click the entity to get into color scheme and brightness control.

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[ X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[ X ] Have made sure I am using the latest version of the plugin.

[ X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[ X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
