### ISSUE TITLE
Fallback to toggle for switches

### ISSUE THREAD

**Issue by NicoBijl** [thomasloven/lovelace-slider-entity-row#60]
Hi, first of all, thanks for this your really nice custom cards!

I'm combining the auto-entities with slider-entity-row and this is when the following happens: 
when I fill a card using all items in a group, and i want to show the lights using the slider-entity-row the following error happens in my browser: 

"Unsupported entity type: switch"

I get why it happens, but it would be really nice if for switches it just has a fallback to show the toggle only. That way i can use the following config to show both ligths and switches from one group. 

```
type: custom:auto-entities
    card:
      title: Livingroom
      type: entities
    filter:
      include:
        - group: group.living_room
          options:
            type: 'custom:slider-entity-row'
```

Could you please add that fallback (maybe with a new option?)

Thanks!

**Comment by thomasloven** [comment]
Or you could include the entities in two steps

This should do it:
```yaml
include:
  - group: group.living_room
    domain: light
    options:
      type: custom:slider-entity-row
  - group: group.living_room
    domain: /^(light)/
```
