### ISSUE TITLE
V4 min/max no longer working 

### ISSUE THREAD

**Issue by Sku1ly** [thomasloven/lovelace-slider-entity-row#63]
My Home Assistant version: 0.965

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Setting a maximum value on a light 

What I expected to happen: Slider to not go below 29 and not above 30

What happened instead: Slider can go through full 100 range 

**Minimal** steps to reproduce: Set a dimmer light with a max/min

```yaml
# The least ammount of code possible to reproduce my error

entities:
  - entity: light.porch
    max: 30
    min: 29
    toggle: true
    type: 'custom:slider-entity-row'
show_header_toggle: false
title: Outside
type: entities



# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[ x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x ] Have made sure I am using the latest version of the plugin.

[ x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
