### ISSUE TITLE
Cover possible improvements

### ISSUE THREAD

**Issue by bruxy70** [thomasloven/lovelace-slider-entity-row#64]
Thanks for adding the attribute for tilt. This is awesome!

I have 3 more suggestions for your consideration (not sure if this is the right forum, but I did not find other channel)

- Would it make sense to allow to "reverse" the slider, so that it is fully extended in 100% or closed position? I am aware that it goes against the home assistant standard, but if you look a picture of [roller shutters](https://www.dreamstime.com/stock-illustration-window-rolling-shutters-vector-opened-closed-front-view-isolated-white-illustration-realistic-roller-image97357405), the way the standard slider works makes no sense. It would make much more sense for the slider to be "retracted" when the shutter is "open", and "extended" when the shutter is "closed" (whilst the standard is retracted for closed, extended for open). I just can't get used to it.
- The full_row option allows hiding both the name and the icon. Would it make sense to separate the two? E.g. to only show the icon, but not the name (or vice versa)?
- When using the attribute, it shows the same icon as the position. If I add both next to each other, it is not obvious which is which. Would it make sense to allow configuring a custom icon (or custom title)?

Thanks for your great contribution!

**Comment by thomasloven** [comment]
- You can probably wrap that in a [template cover](https://www.home-assistant.io/components/cover.template/) to create a new one that works backwards.
- I don't think that would be worth the ammount of work required. That part of the row uses the built-in entity-row, so I'd have to modify that too to remove the space left by the name.
You could just add `name: " "` to leave it blank, though.
- Did you [try it](https://www.home-assistant.io/lovelace/entities/#icon)?

**Comment by bruxy70** [comment]
@thomasloven , I've tried to re-map the cover, but could not find a way to do that. When I reverse the position, it will screw up the arrows that close and open the cover. It will disable the wrong arrow button at the open/closed position. I've also tried to map closed and open position to different values, but could not find a working combination. I made a custom card that I use right now. But it is not written well (so I did not even share it), and yours is much better.
![image](https://user-images.githubusercontent.com/44951610/62578002-6200ab80-b8a0-11e9-8796-5ade0f2942ed.png)

Never mind, will keep using mine.
Thanks for trying to help anyhow.

**Comment by thomasloven** [comment]
Works for me...
```
cover:
  - platform: template
    covers:
      backwards:
        position_template: "{{ 100 - (state_attr('cover.window', 'current_position')|float) }}"
        set_cover_position:
          - service: cover.set_cover_position
            data_template:
              entity_id: cover.window
              position: {{ 100 - position }}
```
![0xUiEQBWOp](https://user-images.githubusercontent.com/1299821/62599964-efb6b800-b8ed-11e9-9a47-74e83ded7b9c.gif)
