### ISSUE TITLE
white_value for light domain

### ISSUE THREAD

**Issue by thermseekr** [thomasloven/lovelace-slider-entity-row#70]
I suggest including white_value attribute setting under light domain, for adjusting the brightness of white leds in RGBW bulbs and LED strips.

**Comment by thermseekr** [comment]
Hello Thomas, thanks for your work but I'm sorry, I was unable to make it work. Here's what I have:

```
- type: entities
  entities:
    - type: custom:slider-entity-row
      entity: light.quarto_cama
      name: Cores
      full_row: false
      hide_when_off: true
      step: 1
    - type: custom:slider-entity-row
      entity: light.quarto_cama
      name: Branco
      attribute: white_value
      full_row: false
      hide_when_off: true
      step: 1
```

Color slider (default=brightness) shows correctly. But the slider for white_value keeps showing zero and no sliding control.

<img width="501" alt="Captura de Tela 2019-10-30 às 22 26 22" src="https://user-images.githubusercontent.com/48183960/67911297-cdd37700-fb64-11e9-883f-847ba737fbc1.png">

 In the more-info box you can see the white_value is too around 50%.

<img width="367" alt="Captura de Tela 2019-10-30 às 22 31 17" src="https://user-images.githubusercontent.com/48183960/67911363-06735080-fb65-11e9-9ea4-ce8b730d7838.png">

Which can also be confirmed in State for the entity.

<img width="189" alt="Captura de Tela 2019-10-30 às 22 33 05" src="https://user-images.githubusercontent.com/48183960/67911434-4afeec00-fb65-11e9-8053-55c398ee73c7.png">
