### ISSUE TITLE
Slider_entity_row shows red bar

### ISSUE THREAD

**Issue by PierreScerri** [thomasloven/lovelace-slider-entity-row#71]
My Home Assistant version: 0.98.5

My lovelace configuration method (GUI or yaml):gui

What I am doing: 
fold_entity_row to show one of two input sliders depending on the state of an input_boolean.

What I expected to happen:
Show one of two input_sliders like it used to. (before HACS I think)

What happened instead:
Red Bar - no text 

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
        - head: input_boolean.swimming_season
          items:
            - entity: input_boolean.swimming_season
              states:
                'off':
                  entities:
                    - entity: input_number.run_pool_pump_hours_off_season
                      full_row: true
                      type: 'custom:slider-entity-row'
                  type: entities
                'on':
                  entities:
                    - entity: input_number.run_pool_pump_hours_swimming_season
                      full_row: true
                      type: 'custom:slider-entity-row'
                  type: entities
              type: 'custom:state-switch'
          type: 'custom:fold-entity-row'
# End of code
```

Error messages from the browser console:
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

![Screen Shot 2019-09-11 at 19 09 56](https://user-images.githubusercontent.com/34303331/64719050-c29a8e00-d4c7-11e9-899e-29ea6df23f3f.png)
