### ISSUE TITLE
Lovelace - Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by jonare77** [thomasloven/lovelace-slider-entity-row#76]
My Home Assistant version: 0.100.3

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Problem after upgrade of HA.

What I expected to happen:

What happened instead:

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

- type: module
   url: /local/slider-entity-row.js

# End of code
```

Error messages from the browser console:

After upgrade of HA from 100.1 to 2 and 3. I get the following errors

[frontend.js.latest.201910022] https://my-site/local/slider-entity-row.js:53:8 Uncaught SyntaxError: Unexpected end of input
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X ] Have made sure I am using the latest version of the plugin.

[X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
