### ISSUE TITLE
Slider "jumps" when released

### ISSUE THREAD

**Issue by jayheavner** [thomasloven/lovelace-slider-entity-row#78]
My Home Assistant version: 0.101.2

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
While using the slider inside the fold-entity-row plugin. I drag the slider to a new location.

What I expected to happen:
The slider to remain at the dropped location.

What happened instead:
The slider "jumps" to a different location.

**Minimal** steps to reproduce:

```  
- type: 'custom:fold-entity-row'
   padding: 0
   group_config:
     toggle: false
     type: 'custom:slider-entity-row'
   head:
     label: Light Settings
     type: section
   items:
     - entity: light.bedroom
       name: Bedroom
     - entity: light.dining_room
       name: Dining room
```

Error messages from the browser console:
```
slider-entity-row.js:1 Uncaught (in promise) TypeError: Cannot read property 'state' of null
    at light.get _value [as _value] (slider-entity-row.js:1)
    at light.get value [as value] (slider-entity-row.js:1)
    at HTMLElement.render (slider-entity-row.js:6)
    at HTMLElement.update (lit-element.js:163)
    at HTMLElement.performUpdate (updating-element.js:508)
    at HTMLElement._enqueueUpdate (updating-element.js:460)
```
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
