### ISSUE TITLE
Error with slider entity

### ISSUE THREAD

**Issue by neuman1812** [thomasloven/lovelace-slider-entity-row#84]
My Home Assistant version: 0.102.0

My lovelace configuration method GUI

**What I am doing:**
Attempting to install Slider-entity-row

**What I expected to happen:**
Slider should appear next to entity.

**What happened instead:**
Error in Logs: local/slider-entity-row.js:7:1 Uncaught SyntaxError: Unexpected token '<

****Minimal** steps to reproduce:**
In Configure UI,  under Raw Config editor I added The following code to the top

```
resources:
  - type: js
    url: /local/card-tools.js
  - type: module
    url: /local/slider-entity-row.js
```
Under My "Entities Card Configuration"  My code is: 

```
entities:
  - entity: light.dining_room_level
    type: 'custom:slider-entity-row'
  - entity: switch.front_door_hall_switch
  - entity: switch.front_porch_light_switch
  - entity: light.bar_light_1
    icon: 'mdi:floor-lamp'
  - entity: light.bar_overhead
    icon: 'mdi:ceiling-light'
show_header_toggle: true
title: First Floor lights
type: entities
```

**Error messages from the browser console:**
`Uncaught SyntaxError: Unexpected token '<'   slider-entity-row.js:7`

**Steps I took to install:** 
I installed slider-entity-row.js by downloading the raw file from [Here](https://github.com/thomasloven/lovelace-slider-entity-row/raw/master/slider-entity-row.js) and it is placed in my .homeassistant/www  directory.  I also installed card-mod.js from the rar file [here](https://github.com/thomasloven/lovelace-card-mod/raw/master/card-mod.js) in the same directory. 

![code](https://user-images.githubusercontent.com/9267886/69512701-0b80b100-0f13-11ea-8f6d-330e8c39ccc1.png)

I also restarted HA after installing and cleared my cache. 

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[ x] Have made sure I am using the latest version of the plugin.

[ x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
