### ISSUE TITLE
Slider tooltip should show the input_select options not the number

### ISSUE THREAD

**Issue by i00** [thomasloven/lovelace-slider-entity-row#95]
My Home Assistant version: 0.106.3
Slider version: 11

My lovelace configuration method (GUI or yaml):
```yaml
# CONFIG:
input_select:
  bin_day:
    name: Bin day
    options:
      - Sunday
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
    icon: 'mdi:trash-can-outline'

# LOVELACE
entities:
  - entity: input_select.bin_day
    type: 'custom:slider-entity-row'
type: entities
```

What I am doing:
Dragging the slider, number shows in the tooltip:
![image](https://user-images.githubusercontent.com/1435262/75743420-b3044f80-5d5c-11ea-9dd0-f59686ededc4.png)

What I expected to happen:
Option value should show

What happened instead:
Number shows in the tooltip:

**Minimal** steps to reproduce:
Enter the configs, drag the slider in the interface

```yaml
# The least ammount of code possible to reproduce my error

# As mentioned above - that is minimal

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
