### ISSUE TITLE
Doesn't work well with custom:fold-entity-row since 0.107

### ISSUE THREAD

**Issue by basnijholt** [thomasloven/lovelace-slider-entity-row#97]
My Home Assistant version: 0.107
Now it looks like:
![image](https://user-images.githubusercontent.com/6897215/76887312-60f61a80-6882-11ea-8f63-3632cc10909d.png)

Before:
![image](https://user-images.githubusercontent.com/6897215/76887505-ae728780-6882-11ea-8171-e8910100d103.png)

Example yaml:
```
entities:
  - entities:
      - light.sphere_1
    head:
      entity: light.living_room_lights
      name: Living
      type: 'custom:slider-entity-row'
    type: 'custom:fold-entity-row'
show_header_toggle: false
title: Lights
type: entities
```

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
