### ISSUE TITLE
Layout issue with Home Assistant 0.107 and small screen (tablet)

### ISSUE THREAD

**Issue by earion68** [thomasloven/lovelace-slider-entity-row#98]
Since upgrading to Home Assistant 0.107.1 the display is going wrong with small screens (such as a tablet in kiosk mode) and the slider overlaps the other columns.

![image](https://user-images.githubusercontent.com/54678154/77073315-5e650380-69ef-11ea-9e5f-6bcc47b215da.png)

**Comment by basnijholt** [comment]
Also reported in https://github.com/thomasloven/lovelace-slider-entity-row/issues/97.

**Comment by epiller** [comment]
Same here! 
P.S. @earion68 Beautiful dashboard you have there!

**Comment by Jurgenn22** [comment]
Same here, in multiple browsers same issue (Mac OS Safari, Google Chrome)

![slider](https://user-images.githubusercontent.com/50082445/77189866-8c724280-6ad8-11ea-87cd-62ec34f7a58f.jpeg)

**Comment by Jurgenn22** [comment]
This works for me. Just trying, I'm not a developer by far. 
![new config](https://user-images.githubusercontent.com/50082445/77203200-2396c480-6af0-11ea-8cf3-b8f6e13a8814.jpeg)
![slider](https://user-images.githubusercontent.com/50082445/77203208-298ca580-6af0-11ea-9afd-6f72c419555f.jpeg)

**Comment by earion68** [comment]
Thanks for the workaround!

**Comment by jaydouble** [comment]
Same here, this is seriously bad for the WAF...

**Comment by rgruyters** [comment]
Yep same issue here. 

<img width="340" alt="Screenshot 2020-03-21 at 12 00 24" src="https://user-images.githubusercontent.com/2082795/77225026-a1e47c80-6b6b-11ea-9369-0e154d7d22c2.png">

**Comment by GaryOkie** [comment]
I really appreciate that you posted a workaround @Jurgenn22!       Limiting the size of the slider was exactly what I was looking into and your post saved me quite a bit of time of CSS trial and error.

**Comment by Jurgenn22** [comment]
Your welcome @GaryOkie! Thx for the "insert code" edit, I did not know that.

**Comment by t9001** [comment]
Great workaround, thanks @Jurgenn22 !
I get good results across different devices by using a %, your mileage may vary...
`type: 'custom:slider-entity-row'
    style: |
      div {
        max-width: 60%;
        margin: auto;
      }`

**Comment by Mariusthvdb** [comment]
dont think a 'hack' in Style should be necessary, nor as per design by Thomas. Giving as much to go on to debug this:

using:
```
  - type: entities
    title: Philips Hue lights
    show_header_toggle: true
    entities:
      - type: custom:slider-entity-row
        entity: light.backdoor_outdoors
      - type: custom:slider-entity-row
        entity: light.gate_outdoors
      - type: custom:slider-entity-row
        entity: light.porch_outdoors
      - type: custom:slider-entity-row
        entity: light.laundry_ceiling
      - type: custom:slider-entity-row
        entity: light.silver_cabinet
        toggle: true
        hide_when_off: true
      - type: custom:slider-entity-row
        entity: light.dining_corner
        toggle: true
        hide_when_off: true
      - type: custom:slider-entity-row
        entity: light.dining_table_lamp_1
        toggle: true
      - type: custom:slider-entity-row
        toggle: true
        entity: light.dining_table_lamp_2
      - type: custom:slider-entity-row
        toggle: true
        entity: light.dining_table_lamp_3
```

resulting in:

<img width="429" alt="Schermafbeelding 2020-03-23 om 23 02 57" src="https://user-images.githubusercontent.com/33354141/77367754-18939c80-6d5b-11ea-8850-72e1cea9c7fe.png">

on Ha 107.5 and current slider-entity-row 11
