### ISSUE TITLE
state shows unavailable instead of Unavailable

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-slider-entity-row#99]
My Home Assistant version: 0.107.5

My lovelace configuration method (GUI or yaml):
yaml

What I am doing:
```
  - type: entities
    title: Philips Hue groups
    show_header_toggle: true
    entities:
      - light.achterdeur
      - light.laundry
      - light.buffet
      - type: custom:slider-entity-row
        entity: light.dining_table
        toggle: true
      - light.living
```
What I expected to happen:

all states to be displayed identically in the developer-tools/state
What happened instead:

entities using slider-entity-row show 'unavailable' instead of 'Unavailable'. This is happening both on light entities as hue groups, see picture below

Paulus suggest this could be happening because 

> translations maybe not used

see: https://github.com/home-assistant/core/issues/33223#issuecomment-603559715
**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

  - type: entities
    title: Philips Hue groups
    show_header_toggle: true
    entities:
      - light.achterdeur
      - light.laundry
      - light.buffet
      - type: custom:slider-entity-row
        entity: light.dining_table
        toggle: true
      - light.living


# End of code
```
<img width="443" alt="Schermafbeelding 2020-03-24 om 22 51 17" src="https://user-images.githubusercontent.com/33354141/77521705-673c5600-6e83-11ea-8db8-6dc5b93f8477.png">
<img width="449" alt="Schermafbeelding 2020-03-24 om 22 51 57" src="https://user-images.githubusercontent.com/33354141/77521716-69061980-6e83-11ea-914f-2cf38326d149.png">

Error messages from the browser console:
none

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[ ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[ ] Have made sure I am using the latest version of the plugin.

[ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
